### ISSUE TITLE
gyp error on npm install electron-rebuild

### ISSUE THREAD

**Issue by nnasoody** [electron/electron-rebuild#104]
Hi folks,

I read through another recently closed post regarding `npm install electron-rebuild` issues to no avail. I've encountered a different error altogether when attempting to install electron rebuild. Here's the lowdown:

Environment: 

- Windows 8.1
- Tried both on node v6.5.0 and v4.5.0 (current version I have is v6.5.0)
- npm v3.10.6
- Python 2.7.10; path already in env vars
- node-gyp set up as outlined [here](https://github.com/nodejs/node-gyp#installation)
- windows-build tools installed via `npm install --global --production windows-build-tools`
- nan package is also globally installed
- msvs_version = "2015" (also set up in my env vars)

Some more information from npm config:

```
user-agent = "npm/3.10.6 node/v6.5.0 win32 x64"

; userconfig C:\Users\some_user\.npmrc
msvs_version = "2015"

; globalconfig C:\Users\some_user\AppData\Roaming\npm\etc\npmrc
msvs_version = "2015"
python = "C:\\Users\\some_user\\.windows-build-tools\\python27\\python.exe"

; builtin config undefined
prefix = "C:\\Users\\some_user\\AppData\\Roaming\\npm"

; default values
...
cache = "C:\\Users\\some_user\\AppData\\Roaming\\npm-cache"
...
globalconfig = "C:\\Users\\some_user\\AppData\\Roaming\\npm\\etc\\npmrc"
globalignorefile = "C:\\Users\\some_user\\AppData\\Roaming\\npm\\etc\\npmignore"
...
node-version = "6.5.0"
...
tmp = "C:\\Users\\some_user\\AppData\\Local\\Temp"
...
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\some_user\\.npmrc"
```

Output for `npm install electron-rebuild`

```
PS C:\projects\desktop> npm install electron-rebuild
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.

> nslog@3.0.0 install C:\projects\desktop\node_modules\nslog
> node-gyp rebuild


C:\projects\desktop\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Users\some_user\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r
ebuild )  else (node "" rebuild )
The filename, directory name, or volume label syntax is incorrect.
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\some_user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\some_user\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\desktop\node_modules\nslog
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Desktop@0.1.2 C:\projects\desktop
`-- UNMET PEER DEPENDENCY regenerator@^0.8.0

npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-linux:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-linux@1.0.2
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-osx:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-osx@1.0.0
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm WARN enoent ENOENT: no such file or directory, open 'C:\projects\desktop\node_modules\build\package.json'
npm WARN regenerator-loader@2.0.0 requires a peer of regenerator@^0.8.0 but none was installed.
npm WARN Desktop@0.1.2 No repository field.
npm WARN Desktop@0.1.2 No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\some_user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-rebuild"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\desktop\npm-debug.log
npm ERR! code 1
PS C:\projects\desktop>

```

I can't seem to figure out what causes this error: 

```

gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\some_user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)

```

Any help is much appreciated.

Thanks.

**Comment by woodev01** [comment]
I would try updating your node to 6.6.0 first and see if that helps.

**Comment by MarshallOfSound** [comment]
Moving to #113
