### ISSUE TITLE
Electron-rebuild will not install

### ISSUE THREAD

**Issue by woodev01** [electron/electron-rebuild#106]
I have looked at past issues for this problem, but none of the answers they had seem to fix my error. Any help would be much appreciated. I have re-installed node and npm. I have all the Visual studio build tools installed. I have run this in Administrator: CMD and in Windows 7.1 SDK command prompt, to no avail. I have installed node-gyp globally, as well as node and npm. I don't know what else I can do. 

My Log: 

```
gyp ERR! build error
gyp ERR! stack Error: 'C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe' failed with exit code: 2148734720
gyp ERR! stack at ChildProcess.onExit (C:\Users\path\to\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13:)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! Command "C:\\Program Files\\nodejs\\node.exe" "C:\\Path\\To\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron-rebuild""
gyp ERR! cwd C:\Path\to\Project\node_modules\nslog
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN Project@1.0.0 No description
npm WARN Project@1.0.0 No repository field.
npm WARN Project@1.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Path\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron-rebuild"
npm ERR! node v6.6.0
npm ERR! npm v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: 'node-gyp rebuild'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Path\To\Project\npm-debug.log 
```

**Comment by enlight** [comment]
Try installing another native module, there are some suggestions at https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#verify-everythings-working to check if the issue is isolated to `electron-rebuild`.

If you see the same MSBuild error I'd suggest reinstalling your Node dev environment,

**Comment by wyemun** [comment]
This is annoying. Have tried literally every method, yet cannot resolve this on a Windows env.

**Comment by MarshallOfSound** [comment]
Merging into #104
