### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by jleppert** [electron/electron-rebuild#107]
Is this module maintained anymore? Even `electron-rebuild --version` doesn't work:

````
electron-rebuild` --version
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.5.0 | darwin | x64
gyp ERR! install error
gyp ERR! stack Error: Invalid version number: true
gyp ERR! stack     at install (/Users/johnathan/.nvm/versions/node/v4.5.0/lib/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/lib/install.js:52:21)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/johnathan/.nvm/versions/node/v4.5.0/lib/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/Users/johnathan/.nvm/versions/node/v4.5.0/lib/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at Object.<anonymous> (/Users/johnathan/.nvm/versions/node/v4.5.0/lib/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:133:1)
gyp ERR! stack     at Module._compile (module.js:409:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:416:10)
gyp ERR! stack     at Module.load (module.js:343:32)
gyp ERR! stack     at Function.Module._load (module.js:300:12)
gyp ERR! stack     at Function.Module.runMain (module.js:441:10)
gyp ERR! stack     at startup (node.js:139:18)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/johnathan/.nvm/versions/node/v4.5.0/bin/node" "/Users/johnathan/.nvm/versions/node/v4.5.0/lib/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=true" "--arch=x64" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"
gyp ERR! cwd /Users/johnathan/devel/mapserver
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/johnathan/.nvm/versions/node/v4.5.0/lib/node_modules/electron-rebuild/lib/spawn.js:55:26)`
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by MarshallOfSound** [comment]
`--version` is a CLI arg to set the Electron version to rebuild against.  Hence you are setting it to a Boolean (true) rather than providing a version string which it expects
