### ISSUE TITLE
Error when running electron-rebuild

### ISSUE THREAD

**Issue by craxal** [electron/electron-rebuild#108]
Trying to run electron-rebuild for Electron 1.4.1 on Windows 10. Tried with Node 4.5.0 and 6.7.0. Tried with both npm 3.10.5 and 3.10.8. I am NOT using Visual Studio Update 3. Always seems to fail on nslog.

```
> keytar@3.0.0 install C:\Code\tests\electron-1.x\node_modules\keytar
> node-gyp rebuild


C:\Code\tests\electron-1.x\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Code\tests\electron-1.x\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  keytar_win.cc
  win_delay_load_hook.cc
     Creating library C:\Code\tests\electron-1.x\node_modules\keytar\build\Release\keytar.lib and object C:\Code\tests\electron-1.x\node_modules\keytar\build\Release\keytar.exp
  Generating code
  Finished generating code
  keytar.vcxproj -> C:\Code\tests\electron-1.x\node_modules\keytar\build\Release\\keytar.node

> electron-prebuilt@0.36.12 postinstall C:\Code\tests\electron-1.x\node_modules\electron-prebuilt
> node install.js


> nslog@3.0.0 install C:\Code\tests\electron-1.x\node_modules\nslog
> node-gyp rebuild


C:\Code\tests\electron-1.x\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Code\tests\electron-1.x\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

gyp ERR! clean error
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Code\tests\electron-1.x\node_modules\nslog\build\Release\nslog.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Code\\tests\\electron-1.x\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Code\tests\electron-1.x\node_modules\nslog
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Code\\tests\\electron-1.x\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=1.4.1" "--arch=ia32"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Code\tests\electron-1.x\node_modules\npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\Code\tests\electron-1.x\node_modules\electron-rebuild\lib\spawn.js:55:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by MarshallOfSound** [comment]
Merging into #104
