### ISSUE TITLE
Module build fails with empty binding.gyp

### ISSUE THREAD

**Issue by pablo-mendoza** [electron/electron-rebuild#1127]
Hello, I'm trying to use audify (https://github.com/almoghamdani/audify) in an electron app with electron-forge.

When the electron-rebuild step runs it tries to rebuild audify build fails with the error at the end.

The module actually uses cmake-js to build and builds fine if build using npm run rebuild. It actually worked fine with electron-rebuild at some point but something updated and it doesn't work anymore. not sure if the issue is in electron-rebuild or node-gyp.

```
\ Building module: audify, Completed: 0gyp: Unable to find targets in build file binding.gyp while trying to load binding.gyp
Error: `gyp` failed with exit code: 1
    at ChildProcess.onCpExit (C:\code\wiservibe\electron\node_modules\@electron\rebuild\node_modules\node-gyp\lib\configure.js:325:16)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\code\wiservibe\electron\node_modules\audify'

Error: node-gyp failed to rebuild 'C:\code\wiservibe\electron\node_modules\audify'
    at ChildProcess.<anonymous> (C:\code\wiservibe\electron\node_modules\@electron\rebuild\lib\module-type\node-gyp\node-gyp.js:118:24)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)


```

**Comment by tarekis** [comment]
This is caused by the same issue as https://github.com/electron/rebuild/issues/1116.

See https://github.com/electron/rebuild/issues/1116#issuecomment-1973877557 for a workaround.

**Comment by pablo-mendoza** [comment]
It doesn't seem like node-rebuild does anything at all when forced to run with node-gyp@10.0.1. It just hangs there claiming to be building but no compiler commands are actually running
