### ISSUE TITLE
Can not rebuild sqlite3 in Windows 7 x64

### ISSUE THREAD

**Issue by mnrafg** [electron/electron-rebuild#156]
I have downloaded sqlite3 `$ npm install --save sqlite3` it works perfect when I try to use it through `$ node sqlite3-test.js` but when I want to load it into my electron main process and use it there, it can not work, so I found that it must be rebuild for electron and I give a shot to electron-rebuild but in result I got the following errors.

**Note:** I already have `g++`, `python 2.7`, `node 6.9.4`, and `node-gyp 3.6.0` and all of them are added to the PATH variable.

````
$ node_modules\.bin\electron-rebuild.cmd
× Rebuild Failed
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.9.4 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.6.2/iojs-v1.6.2.tar.gz
gyp http 200 https://atom.io/download/electron/v1.6.2/iojs-v1.6.2.tar.gz
gyp http GET https://atom.io/download/electron/v1.6.2/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.6.2/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v1.6.2/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.2/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v1.6.2/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.2/win-x64/iojs.lib
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Dev\\MyApp-v0.1.0\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Dev\\MyApp-v0.1.0\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Dev\\MyApp-v0.1.0\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\My User\\.electron-gyp\\.node-gyp\\iojs-1.6.2\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\My User\\.electron-gyp\\.node-gyp\\iojs-1.6.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Dev\\MyApp-v0.1.0\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Dev\\MyApp-v0.1.0\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Dev\\MyApp-v0.1.0\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Dev\MyApp-v0.1.0\node_modules\sqlite3\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Dev\MyApp-v0.1.0\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Dev\\MyApp-v0.1.0\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\Dev\\MyApp-v0.1.0\\node_modules\\sqlite3\\lib\\binding\\electron-v1.6-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v3.1.8/{toolset}/" "--package_name=electron-v1.6-win32-x64.tar.gz"
gyp ERR! cwd C:\Dev\MyApp-v0.1.0\node_modules\sqlite3
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.9.4 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.6.2/iojs-v1.6.2.tar.gz
gyp http 200 https://atom.io/download/electron/v1.6.2/iojs-v1.6.2.tar.gz
gyp http GET https://atom.io/download/electron/v1.6.2/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.6.2/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v1.6.2/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.2/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v1.6.2/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.2/win-x64/iojs.lib
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Dev\\MyApp-v0.1.0\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Dev\\MyApp-v0.1.0\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Dev\\MyApp-v0.1.0\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\My User\\.electron-gyp\\.node-gyp\\iojs-1.6.2\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\My User\\.electron-gyp\\.node-gyp\\iojs-1.6.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Dev\\MyApp-v0.1.0\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Dev\\MyApp-v0.1.0\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Dev\\MyApp-v0.1.0\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Dev\MyApp-v0.1.0\node_modules\sqlite3\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Dev\MyApp-v0.1.0\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Dev\\MyApp-v0.1.0\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\Dev\\MyApp-v0.1.0\\node_modules\\sqlite3\\lib\\binding\\electron-v1.6-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v3.1.8/{toolset}/" "--package_name=electron-v1.6-win32-x64.tar.gz"
gyp ERR! cwd C:\Dev\MyApp-v0.1.0\node_modules\sqlite3
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Dev\MyApp-v0.1.0\node_modules\spawn-rx\lib\src\index.js:262:84)
    at SafeSubscriber.__tryOrUnsub (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:234:16)
    at SafeSubscriber.error (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:195:26)
    at Subscriber._error (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (C:\Dev\MyApp-v0.1.0\node_modules\spawn-rx\lib\src\index.js:236:65)
    at SafeSubscriber.__tryOrSetError (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:243:16)
    at SafeSubscriber.next (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:185:27)
    at Subscriber._next (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:89:18)
    at ReduceSubscriber._complete (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\operator\reduce.js:119:30)
    at ReduceSubscriber.Subscriber.complete (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:114:18)
    at MergeAllSubscriber._complete (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\operator\mergeAll.js:94:30)
    at MergeAllSubscriber.Subscriber.complete (C:\Dev\MyApp-v0.1.0\node_modules\rxjs\Subscriber.js:114:18)
````

**Any help would be greatly appreciated.**

**Comment by MarshallOfSound** [comment]
> MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Dev\MyApp-v0.1.0\node_modules\sqlite3\build\binding.sln]

You need to the c++ build tools for Windows.  You can download them over at http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by adamgoose** [comment]
I have installed the C++ Build tools as instructed, yet I am still getting the same error while trying to rebuild electron with `@google-cloud/storage` and `@google-cloud/vision` installed (I think `grpc` is the problem).

```
PS C:\Users\adame\Code\faceguard> npm run postinstall

> faceguard@0.0.0 postinstall C:\Users\adame\Code\faceguard
> electron-rebuild.cmd

× Rebuild Failed
An unhandled error occurred inside electron-rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framewo
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is
installed elsewhere.  [C:\Users\adame\Code\faceguard\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framewo
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is
installed elsewhere.  [C:\Users\adame\Code\faceguard\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framewo
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is
installed elsewhere.  [C:\Users\adame\Code\faceguard\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framewo
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is
installed elsewhere.  [C:\Users\adame\Code\faceguard\node_modules\grpc\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\adame\Code\faceguard\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\adame\\Code\\faceguard\\node_modules\\node-gyp\\bin\\
node-gyp.js" "rebuild" "--target=1.7.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source
" "--module_name=grpc_node" "--module_path=C:\\Users\\adame\\Code\\faceguard\\node_modules\\grpc\\src\\node\\extension_b
inary" "--host=https://storage.googleapis.com/" "--remote_path=grpc-precompiled-binaries/node/{name}/v1.4.1" "--package_
name=electron-v1.7-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\adame\Code\faceguard\node_modules\grpc
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framewo
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is
installed elsewhere.  [C:\Users\adame\Code\faceguard\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framewo
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is
installed elsewhere.  [C:\Users\adame\Code\faceguard\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framewo
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is
installed elsewhere.  [C:\Users\adame\Code\faceguard\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framewo
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is
installed elsewhere.  [C:\Users\adame\Code\faceguard\node_modules\grpc\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\adame\Code\faceguard\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\adame\\Code\\faceguard\\node_modules\\node-gyp\\bin\\
node-gyp.js" "rebuild" "--target=1.7.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source
" "--module_name=grpc_node" "--module_path=C:\\Users\\adame\\Code\\faceguard\\node_modules\\grpc\\src\\node\\extension_b
inary" "--host=https://storage.googleapis.com/" "--remote_path=grpc-precompiled-binaries/node/{name}/v1.4.1" "--package_
name=electron-v1.7-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\adame\Code\faceguard\node_modules\grpc
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\adame\Code\faceguard\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\adame\Code\faceguard\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (C:\Users\adame\Code\faceguard\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (C:\Users\adame\Code\faceguard\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (C:\Users\adame\Code\faceguard\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\Users\adame\Code\faceguard\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (C:\Users\adame\Code\faceguard\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (C:\Users\adame\Code\faceguard\node_modules\spawn-rx\lib\src\index.js:241:65)
    at SafeSubscriber.__tryOrSetError (C:\Users\adame\Code\faceguard\node_modules\rxjs\Subscriber.js:247:16)
    at SafeSubscriber.next (C:\Users\adame\Code\faceguard\node_modules\rxjs\Subscriber.js:187:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! faceguard@0.0.0 postinstall: `electron-rebuild.cmd`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the faceguard@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adame\AppData\Roaming\npm-cache\_logs\2017-07-22T02_02_31_257Z-debug.log
```

`"postinstall": "./node_modules/.bin/electron-rebuild.cmd"`

**Comment by fritx** [comment]
Btw, can we custom `rebuildArgs` by `--` cli args like `--rebuild-args`?

```js
// src/rebuild.ts
    const rebuildArgs = [
      'rebuild',
      `--target=${this.electronVersion}`,
      `--arch=${this.arch}`,
      `--dist-url=${this.headerURL}`,
      '--build-from-source',

      // custom args
      ' --build-from-source',
      '--sqlite_libname=sqlcipher',
      '--sqlite=`brew --prefix`',
      ////
    ];
```

**Comment by aguynamedben** [comment]
Anybody figure out if we can do what @fritx asks?
