### ISSUE TITLE
Automatic getting version of electron does not work well

### ISSUE THREAD

**Issue by azurinko** [electron/electron-rebuild#189]
C:\_DEV\_theProject (master) (test@1.0.0)
λ npm update electron

> electron@1.7.3 postinstall C:\_DEV\_theProject\node_modules\electron
> node install.js

+ electron@1.7.3
removed 2 packages and updated 1 package in 125.874s

C:\_DEV\_theProject (master) (test@1.0.0)
λ electron-rebuild sqlite3
√ Rebuild Complete

C:\_DEV\_theProject (master) (test@1.0.0)
λ npm start

> test@1.0.0 start C:\_DEV\_theProject
> electron .

App threw an error during load
Error: Cannot find module 'C:\_DEV\_theProject\node_modules\sqlite3\lib\binding\electron-v1.7-win32-x64\node_sqlite3.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\_DEV\_theProject\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\_DEV\_theProject\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Object.<anonymous> (C:\_DEV\_theProject\node_modules\sqlite3\lib\sqlite3.js:190:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

C:\_DEV\_theProject (master) (test@1.0.0)
λ electron-rebuild sqlite3 -v 1.7.3
√ Rebuild Complete

C:\_DEV\_theProject (master) (test@1.0.0)
λ npm start

> test@1.0.0 start C:\_DEV\_theProject
> electron .

OK

**Comment by MarshallOfSound** [comment]
Thanks for the report. This 2017 issue predates a rework of Electron version detection and the described path scheme no longer applies, with no recent activity, so we are closing it as stale. Please open a fresh issue if it still occurs on a current release.
