### ISSUE TITLE
Issue with spread operator

### ISSUE THREAD

**Issue by dland512** [electron/electron-rebuild#200]
I'm getting this error on Ubuntu:

```
# ./node_modules/.bin/electron-rebuild 

/home/root/test/node_modules/electron-rebuild/lib/src/rebuild.js:73
                depKeys.push(...Object.keys(rootPackageJson.dependencies || {}));
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/root/test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/root/test/node_modules/electron-rebuild/src/cli.ts:9:1)
    at Module._compile (module.js:410:26)
```

Seems to be choking on the spread operator. Does `electron-rebuild` itself run under electron's node or the system's node? I'm guessing the system's node, which at version 4.2.6 can't handle the spread operator. Does that sound right? I can't necessarily upgrade it.

Here is my environment info:
```
Ubuntu: 16.04, ARMv7
system node: v4.2.6
npm: 3.5.2
electron: v1.4.16
electron node: 6.5.0
```

It works fine in my dev environment, which is running node 6.11.0.

**Comment by dland512** [comment]
FYI, the problem did seem to be the fact that my system node, which as at `v4.2.6` wasn't new enough to support the spread operator. Once I upgraded to `v6.5.0` the rebuild worked fine.

**Comment by malept** [comment]
Thanks for filing an issue, but according to https://github.com/electron/electron-rebuild/blob/dbd5b278a7e435b7dd7ca7676388c550c1ced3a6/package.json#L30-L32 the minimum Node version for electron-rebuild is Node 6.

**Comment by dland512** [comment]
Checkout [pull request](https://github.com/electron/electron-rebuild/pull/201) to update docs with this info.
