### ISSUE TITLE
NODE_MODULE_VERSION mismatch with node-ffi

### ISSUE THREAD

**Issue by RexSkz** [electron/electron-rebuild#208]
Hello, I'm using electron-rebuild to rebuild [node-ffi](https://github.com/node-ffi/node-ffi) so that I can use it in electron, but an error occurs. Here are some informations, hope they're useful!

# package.json file

```json
{
  "name": "win32-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "electron": "^1.8.1",
    "ffi": "^2.2.0",
    "win32-api": "^1.6.1"
  },
  "devDependencies": {
    "electron-rebuild": "^1.6.0"
  }
}
```

# Commands I executed

```bash
> npm install
// several lines, no error at all

> .\node_modules\.bin\electron-rebuild -f
√ Rebuild Complete

> electron index.js
Error: The module '\\?\C:\Users\rexfg\Desktop\node-win32-test\node_modules\ref\build\Release\binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\rexfg\Desktop\node-win32-test\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\rexfg\Desktop\node-win32-test\node_modules\ref\lib\ref.js:5:47)

> cat node_modules\electron\dist\version
v1.8.1
```

If someone need more information, just let me know, I'll try to provide them :)

**Comment by RexSkz** [comment]
Well, I finally realize it's my fault, **local electron version (v1.8.1) is different from global one (v1.6.11)**.

BTW, if anyone wants to use another version of electron, using `.\node_modules\.bin\electron-rebuild -v ELECTRON_VERSION` is fine, while `ELECTRON_VERSION` is your electron version (no "v", for example, just 1.8.1 is fine).
