### ISSUE TITLE
Can not rebuild ffi in win 10 x64

### ISSUE THREAD

**Issue by beautycss** [electron/electron-rebuild#210]
I have installed ref and ffi modules. error occured while run electron-rebuild.
I want to package a 32 bit app by electron for the 32 bit systems.

What I have Installed:
System: Win 10 x64
NodeJS: 8.3.0 32 bit
NPM: 5.3.0
Electron: 1.7.9 32 bit
node-gyp: 3.6.2
electron-rebuild: 1.6.0
electron-prebuilt: 1.4.13
python: 2.7
vs2013

```
λ electron-rebuild
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.3.0 | win32 | ia32
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\node\\nvm\\v8.3.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\projects\\electron-yle\\node_modules\\ffi\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\node\\nvm\\v8.3.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.electron-gyp\\.node-gyp\\iojs-1.7.9\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.electron-gyp\\.node-gyp\\iojs-1.7.9',
gyp info spawn args   '-Dnode_gyp_dir=C:\\node\\nvm\\v8.3.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Administrator\\.electron-gyp\\.node-gyp\\iojs-1.7.9\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\projects\\electron-yle\\node_modules\\ffi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\projects\\electron-yle\\node_modules\\ffi\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ�����ӡ�/m�����ء�
  Building assembly file ..\..\..\deps\libffi\src\x86\win32.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win32.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\projects\electron-yle\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
..\src\ffi.cc(111): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(114): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(123): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(124): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(125): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(126): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(132): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\ia32\iojs.lib : fatal error LNK1106: �ļ���Ч�������
��:  �޷����ҵ� 0x26371E [C:\projects\electron-yle\node_modules\ffi\build\ffi_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\node\\nvm\\v8.3.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.9" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\projects\electron-yle\node_modules\ffi
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.3.0 | win32 | ia32
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\node\\nvm\\v8.3.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\projects\\electron-yle\\node_modules\\ffi\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\node\\nvm\\v8.3.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.electron-gyp\\.node-gyp\\iojs-1.7.9\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.electron-gyp\\.node-gyp\\iojs-1.7.9',
gyp info spawn args   '-Dnode_gyp_dir=C:\\node\\nvm\\v8.3.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Administrator\\.electron-gyp\\.node-gyp\\iojs-1.7.9\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\projects\\electron-yle\\node_modules\\ffi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\projects\\electron-yle\\node_modules\\ffi\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ�����ӡ�/m�����ء�
  Building assembly file ..\..\..\deps\libffi\src\x86\win32.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win32.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\projects\electron-yle\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
..\src\ffi.cc(111): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(114): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(123): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(124): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(125): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(126): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
..\src\ffi.cc(132): warning C4996: 'v8::Object::ForceSet': ������Ϊ�ѷ�� [C:\projects\electron-yle\node_modules\
ffi\build\ffi_bindings.vcxproj]
          C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\deps\v8\include\v8.h(2967) : �μ���v8::Object::F
orceSet��������
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.7.9\ia32\iojs.lib : fatal error LNK1106: �ļ���Ч�������
��:  �޷����ҵ� 0x26371E [C:\projects\electron-yle\node_modules\ffi\build\ffi_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\node\\nvm\\v8.3.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.9" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\projects\electron-yle\node_modules\ffi
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:247:16)
    at SafeSubscriber.next (C:\node\nvm\v8.3.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:187:27)
```

**Comment by gdutwyg** [comment]
do you handle it？  i met same question。  @beautycss

**Comment by beautycss** [comment]
@gdutwyg not yet. Still this error.
How did you resolve it? Thanks.

**Comment by gdutwyg** [comment]
i handle it. maybe your  installed  environment  is Incomplete， you can see this article
[node-gyp](https://www.npmjs.com/package/node-gyp)

**Comment by beautycss** [comment]
@gdutwyg  Thanks!!

**Comment by yuxiaokuai** [comment]
@beautycss I have the same problem with you, i have reinstall node-gyp, but not works. how did you handle it.

**Comment by BONDbATIF** [comment]
I also having same but no idea how to deal with this problem.

**Comment by sanjevirau** [comment]
I too have the same problem. Any solution guys?

**Comment by elizalc** [comment]
This works for me on Windows.
`npm config set python /path/to/executable/python2.7`

**Comment by EricPeter** [comment]
@elizalc 
How do you do that in Linux ubuntu19.04
npm config set python /path/to/executable/python2.7

**Comment by EricPeter** [comment]
@electron-bot @elizalc 
Uncaught Error: The module '/home/ericpeter/Desktop/new/opencv4nodejs/build/Release/opencv4nodejs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
can some help me please

**Comment by BrunoGusChagas** [comment]
@EricPeter same problem here ? Did you solve it ?

**Comment by MarshallOfSound** [comment]
Thanks for the report. This is a 2017 toolchain build failure against a long-unsupported stack with no repro on current versions, so we are closing it as stale. Please open a fresh issue if you still hit this on a current release.
