### ISSUE TITLE
I can not rebuild. Maybe because of MSbuild

### ISSUE THREAD

**Issue by omajuca** [electron/electron-rebuild#211]
I tried to rebuild ref module.
But I can't rebuild and prompt shows me that error code.

E:\ONEDRIVE\프로젝트\비서 프로젝트\demo>node_modules\.bin\electron-rebuild.cmd
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.2.0 | win32 | x64
gyp info spawn C:\Users\S\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\ref\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\S\\.electron-gyp\\.node-gyp\\iojs-1.7.9\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\S\\.electron-gyp\\.node-gyp\\iojs-1.7.9',
gyp info spawn args   '-Dnode_gyp_dir=E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\S\\.electron-gyp\\.node-gyp\\iojs-1.7.9\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\ref',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\ref\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�� �ַ���� ������Ʈ�� �� ���� �ϳ��� ����մϴ�. ���� ��带 ����Ϸ��� "/m" ����ġ�� �߰��Ͻʽÿ�.
  binding.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: 'E:\ONEDRIVE\CA��IA�ר���\��n���� CA��IA�ר���\demo\node_modules\node-gyp\src\win_delay_load_hook.cc': No such file or directory [E:\ONEDRIVE\������Ʈ\�� ������Ʈ\demo\node_modules\ref\build\binding.vcxproj]
..\src\binding.cc(643): warning C4996: 'Nan::ForceSet': was declared deprecated (compiling source file ..\src\binding.cc) [E:\ONEDRIVE\������Ʈ\�� ������Ʈ\demo\node_modules\ref\build\binding.vcxproj]
  e:\onedrive\������Ʈ\�� ������Ʈ\demo\node_modules\nan\nan_maybe_43_inl.h(116): note: see declaration of 'Nan::ForceSet' (compiling source file ..\src\binding.cc)
..\src\binding.cc(644): warning C4996: 'Nan::ForceSet': was declared deprecated (compiling source file ..\src\binding.cc) [E:\ONEDRIVE\������Ʈ\�� ������Ʈ\demo\node_modules\ref\build\binding.vcxproj]
  e:\onedrive\������Ʈ\�� ������Ʈ\demo\node_modules\nan\nan_maybe_43_inl.h(116): note: see declaration of 'Nan::ForceSet' (compiling source file ..\src\binding.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\ref
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.2.0 | win32 | x64
gyp info spawn C:\Users\S\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\ref\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\S\\.electron-gyp\\.node-gyp\\iojs-1.7.9\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\S\\.electron-gyp\\.node-gyp\\iojs-1.7.9',
gyp info spawn args   '-Dnode_gyp_dir=E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\S\\.electron-gyp\\.node-gyp\\iojs-1.7.9\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\ref',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\ref\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�� �ַ���� ������Ʈ�� �� ���� �ϳ��� ����մϴ�. ���� ��带 ����Ϸ��� "/m" ����ġ�� �߰��Ͻʽÿ�.
  binding.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: 'E:\ONEDRIVE\CA��IA�ר���\��n���� CA��IA�ר���\demo\node_modules\node-gyp\src\win_delay_load_hook.cc': No such file or directory [E:\ONEDRIVE\������Ʈ\�� ������Ʈ\demo\node_modules\ref\build\binding.vcxproj]
..\src\binding.cc(643): warning C4996: 'Nan::ForceSet': was declared deprecated (compiling source file ..\src\binding.cc) [E:\ONEDRIVE\������Ʈ\�� ������Ʈ\demo\node_modules\ref\build\binding.vcxproj]
  e:\onedrive\������Ʈ\�� ������Ʈ\demo\node_modules\nan\nan_maybe_43_inl.h(116): note: see declaration of 'Nan::ForceSet' (compiling source file ..\src\binding.cc)
..\src\binding.cc(644): warning C4996: 'Nan::ForceSet': was declared deprecated (compiling source file ..\src\binding.cc) [E:\ONEDRIVE\������Ʈ\�� ������Ʈ\demo\node_modules\ref\build\binding.vcxproj]
  e:\onedrive\������Ʈ\�� ������Ʈ\demo\node_modules\nan\nan_maybe_43_inl.h(116): note: see declaration of 'Nan::ForceSet' (compiling source file ..\src\binding.cc)
gyp ERR! build error
**gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1**
gyp ERR! stack     at ChildProcess.onExit (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\ONEDRIVE\\프로젝트\\비서 프로젝트\\demo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\ref
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\rxjs\Subscriber.js:185:22)

E:\ONEDRIVE\프로젝트\비서 프로젝트\demo>npm install --save electron-prebuilt
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron

> electron-prebuilt@1.4.13 postinstall E:\ONEDRIVE\프로젝트\비서 프로젝트\demo\node_modules\electron-prebuilt
> node install.js

npm WARN demo@1.0.0 No description
npm WARN demo@1.0.0 No repository field.

+ electron-prebuilt@1.4.13
added 1 package in 5.336s

I searched this problem in google. And I followed 'node-gyp install' . But It couldn't help me.

please help me masters!!

**Comment by jrobeson** [comment]
I've seen lots of bugs on node projects related to non-ascii characters in paths. I wonder if that's the case here.

**Comment by MarshallOfSound** [comment]
Thanks for the report. This is a 2017 local MSBuild/toolchain problem on a long-dead stack with no repro, so we are closing it as stale. Please open a fresh issue if you still hit this on a current release.
