### ISSUE TITLE
Not work with Ethreum web3

### ISSUE THREAD

**Issue by haomaggiewu** [electron/electron-rebuild#216]
Platform: darwin
node: v8.0.0
npm: v5.0.0
electron: v1.6.2

**I installed the Ethreum [web3](https://github.com/ethereum/web3.js/) module
When run electron., it shows:**

```
Error: The module '/Users/Maggie/Documents/RA/FirstElectron/node_modules/scrypt/build/Release/scrypt.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

**Then I installed electron rebuild**
`./node_modules/.bin/electron-rebuild`

**I get error message**
```
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.0.0 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/Maggie/Documents/RA/FirstElectron/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maggie/Documents/RA/FirstElectron/node_modules/ed25519/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maggie/Documents/RA/FirstElectron/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maggie/.electron-gyp/.node-gyp/iojs-1.6.15/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Maggie/.electron-gyp/.node-gyp/iojs-1.6.15',
gyp info spawn args   '-Dnode_gyp_dir=/Users/Maggie/Documents/RA/FirstElectron/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Maggie/.electron-gyp/.node-gyp/iojs-1.6.15/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Maggie/Documents/RA/FirstElectron/node_modules/ed25519',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
../src/ed25519/keypair.c:2:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^
1 error generated.
make: *** [Release/obj.target/ed25519/src/ed25519/keypair.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Maggie/Documents/RA/FirstElectron/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/Maggie/.nvm/versions/node/v8.0.0/bin/node" "/Users/Maggie/Documents/RA/FirstElectron/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.15" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /Users/Maggie/Documents/RA/FirstElectron/node_modules/ed25519
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.0.0 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/Maggie/Documents/RA/FirstElectron/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maggie/Documents/RA/FirstElectron/node_modules/ed25519/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maggie/Documents/RA/FirstElectron/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Maggie/.electron-gyp/.node-gyp/iojs-1.6.15/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Maggie/.electron-gyp/.node-gyp/iojs-1.6.15',
gyp info spawn args   '-Dnode_gyp_dir=/Users/Maggie/Documents/RA/FirstElectron/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Maggie/.electron-gyp/.node-gyp/iojs-1.6.15/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Maggie/Documents/RA/FirstElectron/node_modules/ed25519',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
../src/ed25519/keypair.c:2:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^
1 error generated.
make: *** [Release/obj.target/ed25519/src/ed25519/keypair.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Maggie/Documents/RA/FirstElectron/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/Maggie/.nvm/versions/node/v8.0.0/bin/node" "/Users/Maggie/Documents/RA/FirstElectron/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.15" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /Users/Maggie/Documents/RA/FirstElectron/node_modules/ed25519
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/Maggie/Documents/RA/FirstElectron/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/Users/Maggie/Documents/RA/FirstElectron/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.error (/Users/Maggie/Documents/RA/FirstElectron/node_modules/rxjs/Subscriber.js:197:26)
    at Subscriber._error (/Users/Maggie/Documents/RA/FirstElectron/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (/Users/Maggie/Documents/RA/FirstElectron/node_modules/rxjs/Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (/Users/Maggie/Documents/RA/FirstElectron/node_modules/rxjs/Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (/Users/Maggie/Documents/RA/FirstElectron/node_modules/rxjs/Subscriber.js:102:18)
    at SafeSubscriber._next (/Users/Maggie/Documents/RA/FirstElectron/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (/Users/Maggie/Documents/RA/FirstElectron/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.next (/Users/Maggie/Documents/RA/FirstElectron/node_modules/rxjs/Subscriber.js:185:22)
```

Do you have any idea?

**Comment by malept** [comment]
Seems like you need the OpenSSL headers installed.

**Comment by barbalex** [comment]
I have same problem.

What does above answer mean?:

> Seems like you need the OpenSSL headers installed.

**Comment by barbalex** [comment]
What are OpenSSL headers and how can I install them?

**Comment by malept** [comment]
Headers are a C library's declaration of their API to other C/C++/etc library/applications. Installing them is different on each host platform, I would look on StackOverflow for that answer, as that is not particularly specific to electron-rebuild.

**Comment by barbalex** [comment]
@malept thanks for helping. I had to work through a slew of problems but finally did manage to get past this error. To the next :-(
