### ISSUE TITLE
Unable to find electron-prebuilt's version number, either install it or specify an explicit version

### ISSUE THREAD

**Issue by VisWong** [electron/electron-rebuild#238]
Error: Unable to find electron-prebuilt's version number, either install it or specify an explicit version
at Object. (d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:80:19)
at Generator.next ()
at d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:8:71
at new Promise ()
at __awaiter (d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:4:12)
at d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:69:8
at Object. (d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:145:4)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)

Here is the console output after I following the instruction provided by the node-serialport project.

I did the below steps:
npm install --save-dev electron-rebuild
Add electron-rebuild to your project's package.json's install hook
Run npm install

Any one has ideas of the issue?

electron version 1.8.4
node version 8.11.1
os win 10

**Comment by meghnad-globalids** [comment]
try installing node_modules again using npm install.worked for me
