### ISSUE TITLE
Issue on Windows 10 with robotjs module

### ISSUE THREAD

**Issue by quinton-ashley** [electron/electron-rebuild#241]
```
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.11.3 | win32 | x64
gyp http GET https://atom.io/download/electron/v2.0.3/iojs-v2.0.3.tar.gz
gyp http 200 https://atom.io/download/electron/v2.0.3/iojs-v2.0.3.tar.gz
gyp http GET https://atom.io/download/electron/v2.0.3/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v2.0.3/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v2.0.3/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v2.0.3/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v2.0.3/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v2.0.3/win-x64/iojs.lib
gyp info spawn C:\Users\quint\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'E:\\dev\\apps\\qodemate\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\dev\\apps\\qodemate\\node_modules\\robotjs\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\dev\\apps\\qodemate\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\quint\\.electron-gyp\\.node-gyp\\iojs-2.0.3\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\quint\\.electron-gyp\\.node-gyp\\iojs-2.0.3',
gyp info spawn args   '-Dnode_gyp_dir=E:\\dev\\apps\\qodemate\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\quint\\.electron-gyp\\.node-gyp\\iojs-2.0.3\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\dev\\apps\\qodemate\\node_modules\\robotjs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\dev\\apps\\qodemate\\node_modules\\robotjs\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\v141\Toolset.targets(36,5): error MSB8036: The Windows SDK version 10.0.16299.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [E:\dev\apps\qodemate\node_modules\robotjs\build\robotjs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\dev\apps\qodemate\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\dev\\apps\\qodemate\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.3" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd E:\dev\apps\qodemate\node_modules\robotjs
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.11.3 | win32 | x64
gyp http GET https://atom.io/download/electron/v2.0.3/iojs-v2.0.3.tar.gz
gyp http 200 https://atom.io/download/electron/v2.0.3/iojs-v2.0.3.tar.gz
gyp http GET https://atom.io/download/electron/v2.0.3/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v2.0.3/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v2.0.3/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v2.0.3/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v2.0.3/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v2.0.3/win-x64/iojs.lib
gyp info spawn C:\Users\quint\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'E:\\dev\\apps\\qodemate\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\dev\\apps\\qodemate\\node_modules\\robotjs\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\dev\\apps\\qodemate\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\quint\\.electron-gyp\\.node-gyp\\iojs-2.0.3\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\quint\\.electron-gyp\\.node-gyp\\iojs-2.0.3',
gyp info spawn args   '-Dnode_gyp_dir=E:\\dev\\apps\\qodemate\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\quint\\.electron-gyp\\.node-gyp\\iojs-2.0.3\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\dev\\apps\\qodemate\\node_modules\\robotjs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\dev\\apps\\qodemate\\node_modules\\robotjs\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\v141\Toolset.targets(36,5): error MSB8036: The Windows SDK version 10.0.16299.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [E:\dev\apps\qodemate\node_modules\robotjs\build\robotjs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\dev\apps\qodemate\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\dev\\apps\\qodemate\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.3" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd E:\dev\apps\qodemate\node_modules\robotjs
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (E:\dev\apps\qodemate\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (E:\dev\apps\qodemate\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (E:\dev\apps\qodemate\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (E:\dev\apps\qodemate\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (E:\dev\apps\qodemate\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (E:\dev\apps\qodemate\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (E:\dev\apps\qodemate\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (E:\dev\apps\qodemate\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (E:\dev\apps\qodemate\node_modules\rxjs\Subscriber.js:251:16)
    at SafeSubscriber.next (E:\dev\apps\qodemate\node_modules\rxjs\Subscriber.js:191:27)

```

**Comment by PythonDevOp** [comment]
On Windows 7x64, this fixed it for me:

1. Go to the following path - "C:\Program Files (x86)\Microsoft Visual Studio\Installer" and run the `Visual Studio Installer`
2. When open, click on `Modify`
3. Click on `Visual C++ Build Tools`
4. Select the  `VC++ 2015.3 v14.00 (v140) toolset for desktop`  check box on the right
5. Install and restart the computer

This is assuming that you ran `npm install --global --production windows-build-tools` command. Instructions for getting electron-rebuild running depend on having node-gyp setup. Those instructions can be found [here](https://github.com/nodejs/node-gyp).

**Comment by quinton-ashley** [comment]
I'm on Windows 10 and found the solution already.  I used npm rebuild as specified by the robotjs docs on how to build for electron.  If anyone else is interested see <http://robotjs.io/docs/electron>.
