### ISSUE TITLE
Error: Module did not self-register

### ISSUE THREAD

**Issue by starkos** [electron/electron-rebuild#246]
I'm trying to get an electron-forge project up and running with a private native module, 

I created a minimal sample that demonstrates the issue, attached.

[native-test.zip](https://github.com/electron/electron-rebuild/files/2254264/native-test.zip)

I ran it like:

    $ npx electron-forge init native-test
    $ cd native-test
    $ yarn install
    $ yarn start

Which gives the result:

```
App threw an error during load
Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Mira/Temp/native-test/node_modules/my-native-module/index.js:1:181)
    at Object.<anonymous> (/Users/Mira/Temp/native-test/node_modules/my-native-module/index.js:11:3)
```

I also tried skipping `yarn start` and doing this instead:

    $ ./node_modules/.bin/electron-rebuild
    $ ./node_modules/.bin/electron .

Same result.

Been googling this for a while, but not finding anything that seems useful. Have you seen this before?

Thanks!

**Comment by starkos** [comment]
Oh ****…I missed the file that calls `NODE_MODULE`. Sorry for wasting your time with that.
