### ISSUE TITLE
ERROR : "Could not detect abi for version 3.0.0 and runtime electron."

### ISSUE THREAD

**Issue by mikestopcontinues** [electron/electron-rebuild#251]
Installing my own version of `node-abi` fixed the issue, but I figure you guys ought to do it too. :)

```
    "electron": "3.0.0",
    "electron-rebuild": "1.8.2",
```

```
> electron-rebuild -f -w sqlite3

⠋ Searching dependency tree
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 3.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 3.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/Users/msc/Code/wordkeeper/node_modules/node-abi/index.js:30:9)
    at new Rebuilder (/Users/msc/Code/wordkeeper/node_modules/electron-rebuild/lib/src/rebuild.js:64:28)
    at rebuildWithOptions (/Users/msc/Code/wordkeeper/node_modules/electron-rebuild/lib/src/rebuild.js:316:23)
    at Object.doRebuild [as rebuild] (/Users/msc/Code/wordkeeper/node_modules/electron-rebuild/lib/src/rebuild.js:323:16)
    at Object.<anonymous> (/Users/msc/Code/wordkeeper/node_modules/electron-rebuild/lib/src/cli.js:114:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/msc/Code/wordkeeper/node_modules/electron-rebuild/lib/src/cli.js:5:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! wordkeeper@0.1.0 postinstall: `electron-rebuild -f -w sqlite3`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the wordkeeper@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/msc/.npm/_logs/2018-09-21T19_52_09_503Z-debug.log
```

**Comment by MarshallOfSound** [comment]
The version of node-abi that supports 3.0.0 is node-abi@2.4.4.

We currently depend on `^2.0.0` so if you install / upgrade electron-rebuild you will get a version that supports 3.0.0

**Comment by mikestopcontinues** [comment]
It also must require clearing your npm cache, as I did deleted node-modules and reinstalled. Might be worth updating your docs at least.
