### ISSUE TITLE
Not working with Electron 4.0.1

### ISSUE THREAD

**Issue by Jocs** [electron/electron-rebuild#267]
The error message:

```sh
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 4.0.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 4.0.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/Users/ransixi/Documents/marktext/node_modules/node-abi/index.js:30:9)
    at new Rebuilder (/Users/ransixi/Documents/marktext/node_modules/electron-rebuild/lib/src/rebuild.js:64:28)
    at rebuildWithOptions (/Users/ransixi/Documents/marktext/node_modules/electron-rebuild/lib/src/rebuild.js:316:23)
    at Object.doRebuild [as rebuild] (/Users/ransixi/Documents/marktext/node_modules/electron-rebuild/lib/src/rebuild.js:323:16)
    at Object.<anonymous> (/Users/ransixi/Documents/marktext/node_modules/electron-rebuild/lib/src/cli.js:114:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ransixi/Documents/marktext/node_modules/electron-rebuild/lib/src/cli.js:5:58)
```

**Comment by wv1124** [comment]
me to

**Comment by MarshallOfSound** [comment]
> Updating "node-abi" might help solve this issue if it is a new release of electron

Update `node-abi` 👍
