### ISSUE TITLE
Rebuild with sqlite3 failed because python2.7 is not installed

### ISSUE THREAD

**Issue by SaiKDot** [electron/electron-rebuild#293]
my package.json
```
{
  "name": "reddit",
  "version": "1.0.0",
  "description": "reddit electron app",
  "main": "index.js",
  "scripts": {
    "start": "webpack --mode development && webpack-dev-server  --hot",
    "build": "webpack --mode production",
    "electron": "electron .",
    "rebuild": "electron-rebuild -f -w sqlite3",
    "postinstall": "electron-builder install-app-deps"
  },
  "keywords": [
    "reddit"
  ],
  "author": "BSK",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.18.0",
    "electron": "^4.1.4",
    "electron-reload": "^1.4.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "sqlite3": "^4.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/preset-env": "^7.4.3",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.5",
    "css-loader": "^2.1.1",
    "electron-builder": "^20.39.0",
    "electron-rebuild": "^1.8.4",
    "html-webpack-plugin": "^3.2.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.30.0",
    "webpack-cli": "^3.3.1",
    "webpack-dev-server": "^3.3.1"
  }
}
```

I insatalled 

- npm-gyp
- windows-build-tools
- microsoft visual studio community 2017

when I 'electron-rebuild -f -w sqlite3' it fails.
Here's the error message.

Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> sqlite3@4.0.6 install E:\Projects\Electron\Reddit\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

```
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   unpack_sqlite_dep
>   'python2.7' is not recognized as an internal or external command,
>   operable program or batch file.
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [E:\Projects\Electron\Reddit\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
> Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\Projects\Electron\Reddit\node_modules\sqlite3\lib\binding\electron-v4.1-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\Projects\Electron\Reddit\node_modules\sqlite3\lib\binding\electron-v4.1-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.1' (1)
> 
> Error output:
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/electron-v4.1-win32-x64.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.6 and electron@4.1.4 (electron-v4.1 ABI, unknown) (falling back to source compile with node-gyp)
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Windows_NT 10.0.15063
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=E:\\Projects\\Electron\\Reddit\\node_modules\\sqlite3\\lib\\binding\\electron-v4.1-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\Projects\\Electron\\Reddit\\node_modules\\sqlite3\\lib\\binding\\electron-v4.1-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v4.1"
> gyp ERR! cwd E:\Projects\Electron\Reddit\node_modules\sqlite3
> gyp ERR! node -v v10.15.1
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\Projects\Electron\Reddit\node_modules\sqlite3\lib\binding\electron-v4.1-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\Projects\Electron\Reddit\node_modules\sqlite3\lib\binding\electron-v4.1-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.1' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Projects\Electron\Reddit\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> node-pre-gyp ERR! System Windows_NT 10.0.15063
> node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Projects\\Electron\\Reddit\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd E:\Projects\Electron\Reddit\node_modules\sqlite3
> node-pre-gyp ERR! node -v v10.15.1
> node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> node-pre-gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sqlite3@4.0.6 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\SaiK\AppData\Roaming\npm-cache\_logs\2019-04-23T12_47_14_846Z-debug.log
> 
>     at ChildProcess.childProcess.once.code (E:\Projects\Electron\Reddit\node_modules\builder-util\src\util.ts:244:14)
>     at Object.onceWrapper (events.js:277:13)
>     at ChildProcess.emit (events.js:189:13)
>     at maybeClose (internal/child_process.js:970:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> From previous event:
>     at _rebuild (E:\Projects\Electron\Reddit\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
>     at rebuild (E:\Projects\Electron\Reddit\node_modules\app-builder-lib\out\util\yarn.js:163:19)
>     at E:\Projects\Electron\Reddit\node_modules\app-builder-lib\src\util\yarn.ts:20:11
> From previous event:
>     at _installOrRebuild (E:\Projects\Electron\Reddit\node_modules\app-builder-lib\out\util\yarn.js:71:28)
>     at installOrRebuild (E:\Projects\Electron\Reddit\node_modules\app-builder-lib\out\util\yarn.js:55:28)
>     at E:\Projects\Electron\Reddit\node_modules\electron-builder\src\cli\install-app-deps.ts:56:9
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
> From previous event:
>     at _installAppDeps (E:\Projects\Electron\Reddit\node_modules\electron-builder\out\cli\install-app-deps.js:176:26)
>     at installAppDeps (E:\Projects\Electron\Reddit\node_modules\electron-builder\out\cli\install-app-deps.js:144:26)
>     at then (E:\Projects\Electron\Reddit\node_modules\electron-builder\src\cli\cli.ts:46:19)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! reddit@1.0.0 postinstall: `electron-builder install-app-deps`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the reddit@1.0.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\SaiK\AppData\Roaming\npm-cache\_logs\2019-04-23T12_47_14_966Z-debug.log
```

The main issues seems
**'python2.7' is not recognized as an internal or external command**

**(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.**

**Comment by timfish** [comment]
You don't have the right tools installed on your Windows machine to build native code. 

`node-gyp` docs [show you how to do this](https://github.com/nodejs/node-gyp#on-windows). I highly recommend option 1 as it works for most:

> **Option 1**
> Install all the required tools and configurations using Microsoft's windows-build-tools using `npm install --global --production windows-build-tools` from an elevated PowerShell or CMD.exe (run as Administrator).

**Comment by Silbad** [comment]
Hello,
With electron's update to 5.0.0 I have also an issue
```
$ electron-rebuild -f -w sqlite3
- Searching dependency tree
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 5.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 5.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
```

**Comment by abdes-zakari** [comment]
@Silbad  use this version : "electron": "^4.0.2",

**Comment by Silbad** [comment]
@abdes-zakari yes it was my previous version, so we have to wait... :) tks

**Comment by malept** [comment]
For Electron 5, see #294.

**Comment by malept** [comment]
I'm leaving this open as a reminder to add docs for Windows so people know to install `windows-build-tools` as per @timfish's comment: https://github.com/electron/electron-rebuild/issues/293#issuecomment-485844685

**Comment by zhongzhong0505** [comment]
same problem

**Comment by zhongzhong0505** [comment]
![image](https://user-images.githubusercontent.com/15847574/66638711-09ef7800-ec48-11e9-802a-8e770e811769.png)

**Comment by malept** [comment]
I've added a link to the `node-gyp` README's installation section in `electron-rebuild`'s README.
