### ISSUE TITLE
Error: Cannot find module error on Windows (lerna, yarn, workspaces)

### ISSUE THREAD

**Issue by gagarin55** [electron/electron-rebuild#297]
On Windows we got:

```
yarn run v1.13.0
$ C:\projects\emerald-wallet\node_modules\@emeraldwallet\desktop\node_modules\.bin\electron-rebuild
module.js:550
    throw err;
    ^
Error: Cannot find module 'C:\projects\emerald-wallet\node_modules\node_modules\electron-rebuild\lib\src\cli.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
error Command failed with exit code 1.
```

It seems that something wrong with paths here:
```
Error: Cannot find module 'C:\projects\emerald-wallet\node_modules\node_modules\electron-rebuild\lib\src\cli.js
```

The project and its build - https://ci.appveyor.com/project/etcdevteam/emerald-wallet/builds/24301246

We use yarn and lerna with workspaces.

Thank you for any assistance, will be glad to provide more details if needed

**Comment by MarshallOfSound** [comment]
Thanks for the report. This 2019 path-resolution error predates a rewrite of the module layout and search logic, with no repro on current versions, so we are closing it as stale. Please open a fresh issue if it still occurs on a current release.
