### ISSUE TITLE
Not compatible with electron 5.0.1

### ISSUE THREAD

**Issue by quinton-ashley** [electron/electron-rebuild#298]
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 5.0.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 5.0.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/usr/local/lib/node_modules/electron-rebuild/node_modules/node-abi/index.js:30:9)
    at new Rebuilder (/usr/local/lib/node_modules/electron-rebuild/lib/src/rebuild.js:122:28)
    at rebuildWithOptions (/usr/local/lib/node_modules/electron-rebuild/lib/src/rebuild.js:393:23)
    at Object.doRebuild [as rebuild] (/usr/local/lib/node_modules/electron-rebuild/lib/src/rebuild.js:400:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-rebuild/lib/src/cli.js:115:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/electron-rebuild/lib/src/cli.js:5:58)

**Comment by MarshallOfSound** [comment]
> Updating "node-abi" might help solve this issue if it is a new release of electron

You need to upgrade your dependency on `node-abi`.  `yarn upgrade electron-rebuild` or `npm upgrade node-abi --depth=100` will do it
