### ISSUE TITLE
An unhandled error occurred inside electron-rebuild

### ISSUE THREAD

**Issue by eMarek** [electron/electron-rebuild#320]
I am working on an app where I use electron and [johnny-five](http://johnny-five.io/) library. This is my package.json:

```js
{
  "main": "main/index.js",
  "scripts": {
    "start:app": "cross-env NODE_ENV=development electron .",
    "postinstall": "electron-rebuild"
  },
  "devDependencies": {
    "cross-env": "^6.0.3",
    "electron": "^7.0.0",
    "electron-rebuild": "^1.8.6"
  },
  "dependencies": {
    "johnny-five": "^1.3.1",
    "serialport": "^7.1.5"
  }
}
```

Quite straightforward till here. I am on latest macOS Catalina Version 10.15.
Actually everything is quite up to date on my computer:
```
my-computer:my-app my-username$ node -v
v12.13.0
my-computer:my-app my-username$ npm -v
6.12.0
my-computer:my-app my-username$ node-gyp -v
v5.0.5
my-computer:my-app my-username$ yarn -v
1.19.1
my-computer:my-app my-username$ python --version
Python 2.7.16
```

But when I run `electron-rebuild` I get bunch of errors. I think these errors are somehow related to node-gyp or serialport, but I am not really 100%:

```
my-computer:my-app my-username$ electron-rebuild
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/my-username/Documents/my-folder/my-app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/Documents/my-folder/my-app/node_modules/@serialport/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/Documents/my-folder/my-app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/.electron-gyp/7.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/my-username/.electron-gyp/7.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/my-username/Documents/my-folder/my-app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/my-username/.electron-gyp/7.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/my-username/Documents/my-folder/my-app/node_modules/@serialport/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp:329:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:330:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:331:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:378:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
4 errors generated.
make: *** [Release/obj.target/bindings/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/my-username/Documents/my-folder/my-app/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/my-username/Documents/my-folder/my-app/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.0.0" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/my-username/Documents/my-folder/my-app/node_modules/@serialport/bindings
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/my-username/Documents/my-folder/my-app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/Documents/my-folder/my-app/node_modules/@serialport/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/Documents/my-folder/my-app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/.electron-gyp/7.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/my-username/.electron-gyp/7.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/my-username/Documents/my-folder/my-app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/my-username/.electron-gyp/7.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/my-username/Documents/my-folder/my-app/node_modules/@serialport/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp:329:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:330:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:331:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:378:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
4 errors generated.
make: *** [Release/obj.target/bindings/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/my-username/Documents/my-folder/my-app/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/my-username/Documents/my-folder/my-app/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.0.0" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/my-username/Documents/my-folder/my-app/node_modules/@serialport/bindings
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/my-username/Documents/my-folder/my-app/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/my-username/Documents/my-folder/my-app/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/my-username/Documents/my-folder/my-app/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/my-username/Documents/my-folder/my-app/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/my-username/Documents/my-folder/my-app/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/my-username/Documents/my-folder/my-app/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/my-username/Documents/my-folder/my-app/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/my-username/Documents/my-folder/my-app/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/my-username/Documents/my-folder/my-app/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/my-username/Documents/my-folder/my-app/node_modules/rxjs/internal/Subscriber.js:143:22)
```

Is there something I am doing wrong or is there an error in one of the node packages?

**Comment by mircobabini** [comment]
Same here after updating almost everything :)

`  "dependencies": {
    "electron": "^7.1.1",
    "electron-settings": "^3.2.0",
    "etherport": "^0.2.0",
    "johnny-five": "^1.3.1",
    "msgpack5": "^4.2.0",
    "ping": "^0.2.2",
    "serialport": "^8.0.5",
    "ws": "^7.2.0"
  },
  "devDependencies": {
    "electron-prebuilt": "^1.4.13",
    "electron-builder": "^22.1.0",
    "electron-rebuild": "^1.8.6",
    "electron-reload": "^1.5.0"
  },`

**Comment by malept** [comment]
I don't think this is a bug in electron-rebuild. This is an incompatibility with your version of serialport and Node 12.

```
./src/serialport.cpp:331:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.0.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
```

**Comment by eMarek** [comment]
You are right regarding incompatibility. Node 12 is supported since [serialport version 8.0.4](https://github.com/serialport/node-serialport/blob/master/CHANGELOG.md#804-2019-10-27). Just updated all my packages in packages.json to the latest and tested again. Received same error. Must be something else.

**Comment by mircobabini** [comment]
Hey @eMarek I’m having the same issue and the same result, even downgrading nodejs version and upgrading serialport version. So you are right, must be something else.

Do you mind sharing me your code? I’d love to try building your code as well just to see if we really have the same issue.

Seems like we have to fix it by ourselves :/

**Comment by malept** [comment]
I can't reproduce this with the latest versions of everything except Node (currently running Node 8 for reasons unrelated to this issue). Here are the steps I took:

```shell
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install --save serialport
npm install --save-dev electron-packager electron-rebuild
node package.js
```

`package.js` (which is really a very slightly modified version of the example code from the readme):

```javascript
const packager = require('electron-packager')
const { rebuild } = require('electron-rebuild')

packager({
  dir: '.',
  afterCopy: [(buildPath, electronVersion, platform, arch, callback) => {
    rebuild({ buildPath, electronVersion, arch })
      .then(() => callback())
      .catch((error) => callback(error));
  }]
}).then(paths => console.log(paths)).catch(err => console.error(err));
```

@mircobabini you have `"electron-prebuilt": "^1.4.13"` in `devDependencies` for some bizarre reason (that's a super old and unsupported version of Electron). Remove that and move the `electron` dependency into `devDependencies` (instead of `dependencies`).

**Comment by mircobabini** [comment]
@malept thank you. Well, I followed your suggestions and downgraded to node@10.
Still no luck at first try, but then I found a way. The reason was this:


    prebuild-install http request GET https://github.com/node-serialport/node-serialport/releases/download/v2.0.8/bindings-v2.0.8-electron-v69-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/node-serialport/node-serialport/releases/download/v2.0.8/bindings-v2.0.8-electron-v69-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=4.2.12 runtime=electron arch=x64 libc= platform=win32)`

Seems like the serialport bindings needed version was missing from github. Well, since I was using electron 7 it was looking for binaries v75 at beginning. Then downgraded to electron 5 (bindings v70), but still no luck, because there are no ready binaries for many v70 bindings versions.

At the end, downgraded to electron 4.2.12 because I checked and bindings binaries v69 are there: https://github.com/serialport/node-serialport/releases/tag/%40serialport%2Fbindings%402.0.8

But as you can see from the lines above it seems it's looking for the wrong url... right? Byt he way, it's first of all looking for a local cached version, so I manually downloaded it and moved to the local cached location... and it worked.

Well, two questions here:
- Is it possible to build bindings locally where they are missing on the remote serial port repo?
- Why is it looking for the wrong url?

Thank you so much,

**Comment by eMarek** [comment]
@mircobabini, I found it! It is not serialport, it is johnny. Spent days and days for this crap, ffs.

This is my package.json and this is only file in my project folder. Nothing else at the moment.
```
{
  "scripts": {
    "postinstall": "electron-rebuild"
  },
  "devDependencies": {
    "electron": "^7.1.2",
    "electron-rebuild": "^1.8.8"
  },
  "dependencies": {
    "johnny-five": "^1.3.1",
    "serialport": "^8.0.5"
  }
}
```
Electron rebuild fails with errors as posted above. But the reason is not directly in serialport but actually in johnny-five, because it depends on an older serialport version 7.1.5.
```
my-computer:my-app my-username$ yarn list serialport
yarn list v1.19.1
warning package.json: No license field
warning No license field
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ firmata@2.0.0
│  └─ serialport@7.1.5
├─ johnny-five@1.3.1
│  └─ serialport@7.1.5
└─ serialport@8.0.5
```
So under the bottom, yes it is serialport, but we didn't know it. Solution is to force johnny to use newer serialport with `resolutions` property in package.json. Updated package.json:
```
{
  "scripts": {
    "postinstall": "electron-rebuild"
  },
  "devDependencies": {
    "electron": "^7.1.2",
    "electron-rebuild": "^1.8.8"
  },
  "dependencies": {
    "johnny-five": "^1.3.1",
    "serialport": "^8.0.5"
  },
  "resolutions": {
    "serialport": "^8.0.5"
  }
}
```
Run `yarn install` again and `electron-rebuild` will work.

I haven't tested it yet if johnny actually works then in real app by forcing it to use newer serialport, but at least we know what was the problem.

@malept could please rename title to something johnny-five related. Thanks!

**Comment by apemen** [comment]
i use this method than i got this errors
App threw an error during load
Error: Cannot find module '@serialport/bindings'
Require stack:
- D:\project\serialport\node_modules\serialport\lib\index.js
- D:\project\serialport\index.js
- E:\nodejs\node_global\node_modules\electron\dist\resources\default_app.asar\main.js   
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7607:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\project\serialport\node_modules\serialport\lib\index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)

**Comment by mircobabini** [comment]
Check my package.json [here](https://gist.github.com/mircobabini/45eef54b766adf22902cf06a6d3c0f49).

This way it works. :)
