### ISSUE TITLE
electon-rebuild fails for sqlite3

### ISSUE THREAD

**Issue by hadrian625** [electron/electron-rebuild#322]
I am trying to rebuild sqlite3 (tried also with better-sqlite3) against electron but I get this error
Command run 
electron-rebuild -f -w sqlite3

I have installed globally the windows-build-tools

OS: win10
Electron: 2.0.18

Error stack trace
An unhandled error occurred inside electron-rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 status code downloading arm64 iojs.lib
gyp ERR! stack     at Request.<anonymous> (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\electron-rebuild\node_modules\node-gyp\lib\install.js:335:22)
gyp ERR! stack     at emitOne (events.js:121:20)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestResponse (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\request\request.js:1066:10)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "d:\\work\\git\\vue-electron-demo\\vue-electron-demo\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.18" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\better-sqlite3
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

Failed with exit code: 1

Error: gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 status code downloading arm64 iojs.lib
gyp ERR! stack     at Request.<anonymous> (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\electron-rebuild\node_modules\node-gyp\lib\install.js:335:22)
gyp ERR! stack     at emitOne (events.js:121:20)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestResponse (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\request\request.js:1066:10)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:440:20)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "d:\\work\\git\\vue-electron-demo\\vue-electron-demo\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.18" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\better-sqlite3
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (d:\work\git\vue-electron-demo\vue-electron-demo\node_modules\rxjs\internal\Subscriber.js:143:22)

**Comment by Zigridar** [comment]
To do this:
1. Open your package-lock.json file
2. Find the "node-gyp" entry
3. Into the entry replace "version": "5.0.5" to "version": "6.0.1" and remove string "integrity"
4. Reinstall folder "node_modules"
5. Run command "electron-rebuild -f -w sqlite3"

**Comment by EdmarPereira** [comment]
> To do this:
> 
>     1. Open your package-lock.json file
> 
>     2. Find the "node-gyp" entry
> 
>     3. Into the entry replace "version": "5.0.5" to "version": "6.0.1" and remove string "integrity"
> 
>     4. Reinstall folder "node_modules"
> 
>     5. Run command "electron-rebuild -f -w sqlite3"

In my package my node-gyp is "6.0.1" I remove the "integrity" but the error persists
