### ISSUE TITLE
Error: win-x64/node.lib local checksum 'checksum' not match remote 'checksum'

### ISSUE THREAD

**Issue by RHAtUAT** [electron/electron-rebuild#328]
Trying to rebuild serialport for electron, but I keep receiving a checksum error. I have no idea whats causing it. I have `"rebuild": "electron-rebuild -f -w serialport"` in the install hook in package.json, I'm using typescript, have Node LTS 12.13.0, am using VS Code, and am on Windows 10. I can build the module if I follow [node-gyp installation](https://github.com/nodejs/node-gyp#installation), but running `npm run rebuild` returns the following.
```PS D:\GitHub\JavaScript\CoordinateExporter> npm run rebuild

> spaceapplication@1.0.0 rebuild D:\GitHub\JavaScript\CoordinateExporter
> electron-rebuild -f -w serialport

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: win-arm64/node.lib local checksum d5a48e83d9c112a2db16ccf08406b381ea9e86f86b44a2d13712afd84842834d not match remote undefined
gyp ERR! stack     at deref (D:\GitHub\JavaScript\CoordinateExporter\node_modules\node-gyp\lib\install.js:251:20)
gyp ERR! stack     at Request.<anonymous> (D:\GitHub\JavaScript\CoordinateExporter\node_modules\node-gyp\lib\install.js:348:52)
gyp ERR! stack     at Request.emit (events.js:215:7)
gyp ERR! stack     at IncomingMessage.<anonymous> (D:\GitHub\JavaScript\CoordinateExporter\node_modules\request\request.js:1083:12)
gyp ERR! stack     at Object.onceWrapper (events.js:299:28)
gyp ERR! stack     at IncomingMessage.emit (events.js:215:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1183:12)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\NodeJS\\node.exe" "D:\\GitHub\\JavaScript\\CoordinateExporter\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=6.0.8" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd D:\GitHub\JavaScript\CoordinateExporter\node_modules\@serialport\bindings
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: win-arm64/node.lib local checksum d5a48e83d9c112a2db16ccf08406b381ea9e86f86b44a2d13712afd84842834d not match remote undefined
gyp ERR! stack     at deref (D:\GitHub\JavaScript\CoordinateExporter\node_modules\node-gyp\lib\install.js:251:20)
gyp ERR! stack     at Request.<anonymous> (D:\GitHub\JavaScript\CoordinateExporter\node_modules\node-gyp\lib\install.js:348:52)
gyp ERR! stack     at Request.emit (events.js:215:7)
gyp ERR! stack     at IncomingMessage.<anonymous> (D:\GitHub\JavaScript\CoordinateExporter\node_modules\request\request.js:1083:12)
gyp ERR! stack     at Object.onceWrapper (events.js:299:28)
gyp ERR! stack     at IncomingMessage.emit (events.js:215:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1183:12)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\NodeJS\\node.exe" "D:\\GitHub\\JavaScript\\CoordinateExporter\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=6.0.8" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd D:\GitHub\JavaScript\CoordinateExporter\node_modules\@serialport\bindings
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (D:\GitHub\JavaScript\CoordinateExporter\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (D:\GitHub\JavaScript\CoordinateExporter\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (D:\GitHub\JavaScript\CoordinateExporter\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (D:\GitHub\JavaScript\CoordinateExporter\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (D:\GitHub\JavaScript\CoordinateExporter\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (D:\GitHub\JavaScript\CoordinateExporter\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (D:\GitHub\JavaScript\CoordinateExporter\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (D:\GitHub\JavaScript\CoordinateExporter\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (D:\GitHub\JavaScript\CoordinateExporter\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (D:\GitHub\JavaScript\CoordinateExporter\node_modules\rxjs\internal\Subscriber.js:143:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! spaceapplication@1.0.0 rebuild: `electron-rebuild -f -w serialport`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the spaceapplication@1.0.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by RHAtUAT** [comment]
Ran
`npm uninstall electron --save`
`npm uninstall serialport`
`npm uninstall electron-rebuild`
`npm uninstall node-gyp`
deleted modules folder
`npm install electron --save-dev`
`npm install --save-dev electron-rebuild`
`npm install serialport`
`.\node_modules\.bin\electron-rebuild.cmd`
then it all worked fine
