### ISSUE TITLE
Windows rebuild fails - how to change MSBuild?

### ISSUE THREAD

**Issue by HughGrovesArup** [electron/electron-rebuild#331]
Hello, I am having trouble getting rebuild to work on windows.

Here is the error log:

```
PS C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2> .\node_modules\.bin\electron-rebuild
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.4.0 | win32 | x64
gyp info find Python using Python version 2.7.17 found at "C:\Python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.280) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\better-sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hugh.Groves\\.electron-gyp\\6.1.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Hugh.Groves\\.electron-gyp\\6.1.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Hugh.Groves\\\\.electron-gyp\\\\6.1.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\better-sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=6.1.2" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\better-sqlite3
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

Failed with exit code: 7

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.4.0 | win32 | x64
gyp info find Python using Python version 2.7.17 found at "C:\Python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.280) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\better-sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Hugh.Groves\\.electron-gyp\\6.1.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Hugh.Groves\\.electron-gyp\\6.1.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Hugh.Groves\\\\.electron-gyp\\\\6.1.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\better-sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hugh.Groves\\Documents\\VS_Code_Projects\\DesignCheck2Extension\\designcheck2\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=6.1.2" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\better-sqlite3
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

Failed with exit code: 7
    at SafeSubscriber._error (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Users\Hugh.Groves\Documents\VS_Code_Projects\DesignCheck2Extension\designcheck2\node_modules\rxjs\internal\Subscriber.js:143:22)
```

I think this is the key line:

```
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\MSBuild\15.0\Bin\MSBuild.exe ENOENT
```

It maybe looks like gyp is trying to use an incorrect version of msbuild?

I have installed the tools using `npm install --global --production windows-build-tools`. I then tried to follow the guidelines here https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules and tried setting the environment variable `VCTargetsPath` to `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140` (which I have verified exists) but the version of msbuild that is used never changes. I am at a loss! Any help would be much appreciated!

**Comment by malept** [comment]
Set the `GYP_MSVS_VERSION` environment variable to the appropriate Visual Studio version.
