### ISSUE TITLE
electron-rebuild fails due to node-gyp

### ISSUE THREAD

**Issue by biowaffeln** [electron/electron-rebuild#332]
I had an issue running electron-build which failed because of a node-gyp error. The corresponding error message was:

```sh
$ electron-rebuild
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.4.0 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Python27\python.exe"
gyp http GET https://electronjs.org/headers/v5.0.12/node-v5.0.12-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v5.0.12/node-v5.0.12-headers.tar.gz
gyp http GET https://electronjs.org/headers/v5.0.12/SHASUMS256.txt
gyp http GET https://electronjs.org/headers/v5.0.12/win-x86/node.lib
gyp http GET https://electronjs.org/headers/v5.0.12/win-x64/node.lib
gyp http GET https://electronjs.org/headers/v5.0.12/win-arm64/node.lib
gyp http 200 https://electronjs.org/headers/v5.0.12/win-x86/node.lib
gyp http 200 https://electronjs.org/headers/v5.0.12/win-x64/node.lib
gyp http 200 https://electronjs.org/headers/v5.0.12/SHASUMS256.txt
gyp http 403 https://electronjs.org/headers/v5.0.12/win-arm64/node.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 status code downloading arm64 node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\electron-rebuild\node_modules\node-gyp\lib\install.js:335:22)
gyp ERR! stack     at Request.emit (events.js:205:15)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\request\request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:200:13)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:452:22)
gyp ERR! stack     at TLSSocket.emit (events.js:200:13)
gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:275:11)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mkvet\\Documents\\UAL\\Creative_Making_I\\electron-serialport\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=5.0.12" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\@serialport\bindings
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.4.0 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Python27\python.exe"
gyp http GET https://electronjs.org/headers/v5.0.12/node-v5.0.12-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v5.0.12/node-v5.0.12-headers.tar.gz
gyp http GET https://electronjs.org/headers/v5.0.12/SHASUMS256.txt
gyp http GET https://electronjs.org/headers/v5.0.12/win-x86/node.lib
gyp http GET https://electronjs.org/headers/v5.0.12/win-x64/node.lib
gyp http GET https://electronjs.org/headers/v5.0.12/win-arm64/node.lib
gyp http 200 https://electronjs.org/headers/v5.0.12/win-x86/node.lib
gyp http 200 https://electronjs.org/headers/v5.0.12/win-x64/node.lib
gyp http 200 https://electronjs.org/headers/v5.0.12/SHASUMS256.txt
gyp http 403 https://electronjs.org/headers/v5.0.12/win-arm64/node.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 status code downloading arm64 node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\electron-rebuild\node_modules\node-gyp\lib\install.js:335:22)
gyp ERR! stack     at Request.emit (events.js:205:15)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\request\request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:200:13)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:452:22)
gyp ERR! stack     at TLSSocket.emit (events.js:200:13)
gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:275:11)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mkvet\\Documents\\UAL\\Creative_Making_I\\electron-serialport\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=5.0.12" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\@serialport\bindings
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Users\mkvet\Documents\UAL\Creative_Making_I\electron-serialport\node_modules\rxjs\internal\Subscriber.js:143:22)
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I think this is related to the following issue on node-gyp:
https://github.com/nodejs/node-gyp/issues/1933#issuecomment-549921072
According to which bumping the node-gyp to v6.0.1 would fix this.

Should I make a pull request to update the dependency?

**Comment by biowaffeln** [comment]
Nevermind, just saw it's a duplicate of #327
