### ISSUE TITLE
An unhandled error occurred inside electron-rebuild Unable to find electron-prebuilt's version number, either install it or specify an explicit version

### ISSUE THREAD

**Issue by ekofi** [electron/electron-rebuild#334]
Gives 
```
An unhandled error occurred inside electron-rebuild
Unable to find electron-prebuilt's version number, either install it or specify an explicit version

Error: Unable to find electron-prebuilt's version number, either install it or specify an explicit version
    at Object.<anonymous> (C:\Users\tensor\AppData\Roaming\npm\node_modules\electron-rebuild\lib\src\cli.js:81:19)
    at Generator.next (<anonymous>)
    at C:\Users\tensor\AppData\Roaming\npm\node_modules\electron-rebuild\lib\src\cli.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\tensor\AppData\Roaming\npm\node_modules\electron-rebuild\lib\src\cli.js:4:12)
    at C:\Users\tensor\AppData\Roaming\npm\node_modules\electron-rebuild\lib\src\cli.js:70:8
    at Object.<anonymous> (C:\Users\tensor\AppData\Roaming\npm\node_modules\electron-rebuild\lib\src\cli.js:146:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

with `npm install --save-dev electron-rebuild`.

```
  "dependencies": {
    "bcrypt": "^3.0.6",
    "electron": "^6.1.4",
    "nodemon": "^1.19.4"
  },
  "devDependencies": {
    "electron-rebuild": "^1.8.6"
  }
```

**Comment by malept** [comment]
Are you sure that's what  you're running to get that error? `npm install` does not invoke the `electron-rebuild` CLI.

**Comment by ekofi** [comment]
I just typed to console "electron-rebuild", and that's the error.

**Comment by malept** [comment]
You appear to be using a global version of electron-rebuild and not the one that's in the project. I believe that would be `node_modules\.bin\electron-rebuild` on Windows.
