### ISSUE TITLE
Completely random SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by sentialx** [electron/electron-rebuild#335]
Hi, I'm trying to build my Electron app using GitHub Actions (the same occurs on Travis CI) and it sometimes throws me a completely random error (mostly it does work):

```
Error: Traceback (most recent call last):
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2779, in Load
    variables, includes, depth, check, True)
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    includes, True, check)
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 263, in LoadOneBuildFile
    aux_data, includes, check)
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 300, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/home/runner/work/desktop/desktop/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 243, in LoadOneBuildFile
    None)
  File "/home/runner/.electron-gyp/8.0.0-beta.2/include/node/common.gypi", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**OS:** ubuntu-18.04
**Electron version:** 8.0.0-beta.2 (however it was the same even with Electron 6)

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-rebuild` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing?

* Please provide either a failing minimal testcase (with code and CI config) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by sentialx** [comment]
Seems to be working right now after removing package-lock.json, sorry for wasting your time.

**Comment by sentialx** [comment]
Okay, it happened again.

- I'm using `electron-builder`.
- `electron-rebuild -f -o node-window-manager,keytar,extract-file-icon,mouse-hooks`
- [Here](https://github.com/wexond/desktop/runs/308917634) are my CI logs (expand `Build the app`). And [here](https://github.com/wexond/desktop/blob/master/.github/workflows/build.yml) is my workflow config.

**Comment by zangornjak** [comment]
I see you're using the version of this package that has the old `node-gyp` dependency. You could try this https://github.com/electron/electron-rebuild/issues/330#issuecomment-553455657 as a workaround until the developer decides to create a new version.

**Comment by malept** [comment]
1.8.7 has been released. If 1.8.7 does not fix this, please reply with a minimal way to to reproduce this (using a black box with GitHub Actions + electron-builder is very hard to determine what's going on) and I'll reopen the issue.
