### ISSUE TITLE
electron-rebuild fails with electron v8

### ISSUE THREAD

**Issue by mmakrzem** [electron/electron-rebuild#352]
I was using electron v7.1.10 and all was fine.  I just updated electron to v8.0.0 and now when I try to run electron-rebuild I get the following error message:

```
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 8.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 8.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (C:\main\node_modules\node-abi\index.js:30:9)
    at new Rebuilder (C:\main\node_modules\electron-rebuild\lib\src\rebuild.js:126:28)
    at rebuildWithOptions (C:\main\node_modules\electron-rebuild\lib\src\rebuild.js:404:23)
    at Object.doRebuild [as rebuild] (C:\main\node_modules\electron-rebuild\lib\src\rebuild.js:427:16)
    at C:\main\node_modules\electron-rebuild\lib\src\cli.js:120:33
    at Generator.next (<anonymous>)
    at fulfilled (C:\main\node_modules\electron-rebuild\lib\src\cli.js:6:58)
```

I tried adding the latest version of node-abi to my project but I still get the same error

**Comment by mmakrzem** [comment]
never mind.  I discovered I had node-abi v2.13.0 installed.  When I updated it to v.2.14.0, everything started working again.
