### ISSUE TITLE
electron-rebuild sqlite fails napi identifiers not found

### ISSUE THREAD

**Issue by JonathanWoodward** [electron/electron-rebuild#425]
Is there a compatibility issue when using the latest? I get the same problems on both Windows and Linux.

```
PS C:\svn\app\trunk> yarn rebuild
yarn run v1.22.5
$ electron-rebuild -f -w sqlite3
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.11.0 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\jonathan.woodward\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2019 (16.6.30320.27) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\jonathan.woodward\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\svn\\app\\trunk\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\svn\\app\\trunk\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\svn\\app\\trunk\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jonathan.woodward\\.electron-gyp\\7.1.11\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jonathan.woodward\\.electron-gyp\\7.1.11',
gyp info spawn args   '-Dnode_gyp_dir=C:\\svn\\app\\trunk\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\jonathan.woodward\\\\.electron-gyp\\\\7.1.11\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\svn\\app\\trunk\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\svn\\app\\trunk\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\svn\app\trunk\node_modules\sqlite3\build\Release\\nothing.lib
  unpack_sqlite_dep
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> C:\svn\app\trunk\node_modules\sqlite3\build\Release\\sqlite3.lib
  backup.cc
  database.cc
  node_sqlite3.cc
  statement.cc
  win_delay_load_hook.cc
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(402,24): error C3861: 'napi_is_date': identifier not found (compiling source file ..\src\database.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(697,24): error C3861: 'napi_create_date': identifier not found (compiling source file ..\src\database.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(714,24): error C3861: 'napi_get_date_value': identifier not found (compiling source file ..\src\database.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(402,24): error C3861: 'napi_is_date': identifier not found (compiling source file ..\src\backup.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(402,24): error C3861: 'napi_is_date': identifier not found (compiling source file ..\src\statement.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(697,24): error C3861: 'napi_create_date': identifier not found (compiling source file ..\src\backup.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(714,24): error C3861: 'napi_get_date_value': identifier not found (compiling source file ..\src\backup.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(697,24): error C3861: 'napi_create_date': identifier not found (compiling source file ..\src\statement.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(714,24): error C3861: 'napi_get_date_value': identifier not found (compiling source file ..\src\statement.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(402,24): error C3861: 'napi_is_date': identifier not found (compiling source file ..\src\node_sqlite3.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(697,24): error C3861: 'napi_create_date': identifier not found (compiling source file ..\src\node_sqlite3.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(714,24): error C3861: 'napi_get_date_value': identifier not found (compiling source file ..\src\node_sqlite3.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\svn\app\trunk\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\svn\\app\\trunk\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=7.1.11" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\svn\\app\\trunk\\node_modules\\sqlite3\\lib\\binding\\napi-v{napi_build_version}-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v5.0.0/{toolset}/" "--package_name=napi-v{napi_build_version}-win32-x64.tar.gz"
gyp ERR! cwd C:\svn\app\trunk\node_modules\sqlite3
gyp ERR! node -v v14.11.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.11.0 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\jonathan.woodward\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2019 (16.6.30320.27) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\jonathan.woodward\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\svn\\app\\trunk\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\svn\\app\\trunk\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\svn\\app\\trunk\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jonathan.woodward\\.electron-gyp\\7.1.11\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jonathan.woodward\\.electron-gyp\\7.1.11',
gyp info spawn args   '-Dnode_gyp_dir=C:\\svn\\app\\trunk\\node_modules\\electron-rebuild\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\jonathan.woodward\\\\.electron-gyp\\\\7.1.11\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\svn\\app\\trunk\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\svn\\app\\trunk\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\svn\app\trunk\node_modules\sqlite3\build\Release\\nothing.lib
  unpack_sqlite_dep
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> C:\svn\app\trunk\node_modules\sqlite3\build\Release\\sqlite3.lib
  backup.cc
  database.cc
  node_sqlite3.cc
  statement.cc
  win_delay_load_hook.cc
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(402,24): error C3861: 'napi_is_date': identifier not found (compiling source file ..\src\database.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(697,24): error C3861: 'napi_create_date': identifier not found (compiling source file ..\src\database.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(714,24): error C3861: 'napi_get_date_value': identifier not found (compiling source file ..\src\database.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(402,24): error C3861: 'napi_is_date': identifier not found (compiling source file ..\src\backup.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(402,24): error C3861: 'napi_is_date': identifier not found (compiling source file ..\src\statement.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(697,24): error C3861: 'napi_create_date': identifier not found (compiling source file ..\src\backup.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(714,24): error C3861: 'napi_get_date_value': identifier not found (compiling source file ..\src\backup.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(697,24): error C3861: 'napi_create_date': identifier not found (compiling source file ..\src\statement.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(714,24): error C3861: 'napi_get_date_value': identifier not found (compiling source file ..\src\statement.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(402,24): error C3861: 'napi_is_date': identifier not found (compiling source file ..\src\node_sqlite3.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(697,24): error C3861: 'napi_create_date': identifier not found (compiling source file ..\src\node_sqlite3.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\svn\app\trunk\node_modules\node-addon-api\napi-inl.h(714,24): error C3861: 'napi_get_date_value': identifier not found (compiling source file ..\src\node_sqlite3.cc) [C:\svn\app\trunk\node_modules\sqlite3\build\node_sqlite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\svn\app\trunk\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\svn\\app\\trunk\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=7.1.11" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\svn\\app\\trunk\\node_modules\\sqlite3\\lib\\binding\\napi-v{napi_build_version}-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v5.0.0/{toolset}/" "--package_name=napi-v{napi_build_version}-win32-x64.tar.gz"
gyp ERR! cwd C:\svn\app\trunk\node_modules\sqlite3
gyp ERR! node -v v14.11.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\svn\app\trunk\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\svn\app\trunk\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (C:\svn\app\trunk\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (C:\svn\app\trunk\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\svn\app\trunk\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\svn\app\trunk\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\svn\app\trunk\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (C:\svn\app\trunk\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (C:\svn\app\trunk\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\svn\app\trunk\node_modules\rxjs\internal\Subscriber.js:143:22)
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JonathanWoodward** [comment]
I have resolved the issue, one of the following modules was at fault.

<img width="743" alt="napifix" src="https://user-images.githubusercontent.com/54439477/94005102-aa757400-fd95-11ea-9d56-e058bc899d4b.PNG">
