### ISSUE TITLE
Rebuild throw an unhandled error occurred inside electron-rebuild

### ISSUE THREAD

**Issue by Jan307** [electron/electron-rebuild#530]
```
$ electron-rebuild -f -w my-module
⠦ Building module: my-module, Completed: 0gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
⠧ Building module: my-module, Completed: 0gyp http GET https://www.electronjs.org/headers/v10.1.5/node-v10.1.5-headers.tar.gz
⠙ Building module: my-module, Completed: 0gyp WARN install got an error, rolling back install
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/code/node_modules/my-module'.
Error: read ECONNRESET



Error: node-gyp failed to rebuild '/Users/code/node_modules/my-module'.
Error: read ECONNRESET


    at ModuleRebuilder.rebuildNodeGypModule (/Users/code/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at async Rebuilder.rebuildModuleAt (/Users/code/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/Users/code/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /Users/code/node_modules/electron-rebuild/lib/src/cli.js:146:9
```

**Comment by malept** [comment]
> `Error: read ECONNRESET`

This is a network error on your end. You may want to see if you're having problems with connecting to `electronjs.org` or AWS S3.
