### ISSUE TITLE
Cannot rebuild sqlite3

### ISSUE THREAD

**Issue by cyrilfr** [electron/electron-rebuild#546]
I have an Electron app using SQLite and TypeORM. When I try to rebuild the sqlite3 5.0.0 package for my electron version (7.2.3), I get an error:

```
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp: Undefined variable napi_build_version in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/cyril/app/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-58-generic
gyp ERR! command "/usr/bin/node" "/home/cyril/app/node_modules/.bin/node-gyp" "rebuild" "--target=7.2.3" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source" "--module_name=node_sqlite3" "--module_path=/home/cyril/Documents/Vesta/VestaApp3/node_modules/sqlite3/lib/binding/napi-v{napi_build_version}-linux-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v5.0.0/{toolset}/" "--package_name=napi-v{napi_build_version}-linux-x64.tar.gz"
gyp ERR! cwd /home/cyril/app/node_modules/sqlite3
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
```

**Comment by gmantri** [comment]
I ran into the same issue when rebuilding sqlite3 on my Windows machine (did not encounter the issue on my Mac). I added the following line of code to the `variables` section in `binding.gyp` file and that seems to solve the problem:

```
"napi_build_version%":"3"
```

Here's my revised `binding.gyp` file looks like:

```
{
  "includes": [ "deps/common-sqlite.gypi" ],
  "variables": {
      "sqlite%":"internal",
      "sqlite_libname%":"sqlite3",
      "napi_build_version%":"3"
  },
  "targets": [
    {
      "target_name": "<(module_name)",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "xcode_settings": { "GCC_ENABLE_CPP_EXCEPTIONS": "YES",
        "CLANG_CXX_LIBRARY": "libc++",
        "MACOSX_DEPLOYMENT_TARGET": "10.7",
      },
      "msvs_settings": {
        "VCCLCompilerTool": { "ExceptionHandling": 1 },
      },
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"],
      "conditions": [
        ["sqlite != 'internal'", {
            "include_dirs": [
              "<!@(node -p \"require('node-addon-api').include\")", "<(sqlite)/include" ],
            "libraries": [
               "-l<(sqlite_libname)"
            ],
            "conditions": [ [ "OS=='linux'", {"libraries+":["-Wl,-rpath=<@(sqlite)/lib"]} ] ],
            "conditions": [ [ "OS!='win'", {"libraries+":["-L<@(sqlite)/lib"]} ] ],
            'msvs_settings': {
              'VCLinkerTool': {
                'AdditionalLibraryDirectories': [
                  '<(sqlite)/lib'
                ],
              },
            }
        },
        {
            "dependencies": [
              "<!(node -p \"require('node-addon-api').gyp\")",
              "deps/sqlite3.gyp:sqlite3"
            ]
        }
        ]
      ],
      "sources": [
        "src/backup.cc",
        "src/database.cc",
        "src/node_sqlite3.cc",
        "src/statement.cc"
      ],
      "defines": [ "NAPI_VERSION=<(napi_build_version)", "NAPI_DISABLE_CPP_EXCEPTIONS=1" ]
    },
    {
      "target_name": "action_after_build",
      "type": "none",
      "dependencies": [ "<(module_name)" ],
      "copies": [
          {
            "files": [ "<(PRODUCT_DIR)/<(module_name).node" ],
            "destination": "<(module_path)"
          }
      ]
    }
  ]
}
```

Hope this helps.
