### ISSUE TITLE
Electron Rebuild Failed on Better-Sqlite3, exit code 2

### ISSUE THREAD

**Issue by BrianMagus** [electron/electron-rebuild#552]
Any idea what's failing here? I used better-sqlite3 in a previous project and the rebuild worked just fine. This new project has current versions of both node and electron, latest version of node-gyp. Should I roll back to a previous version of one of these?

```
/XXXXXX/node_modules/better-sqlite3/11.1.0/include/node/v8-internal.h:418:38: error: 
      no template named 'remove_cv_t' in namespace 'std'; did you mean
      'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:697:50: note: 
      'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
⠇ Building module: better-sqlite3, Completed: 01 error generated.
make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/XXXXXX/node_modules/better-sqlite3'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/XXXXXX/node_modules/better-sqlite3'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/XXXXXX/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (/XXXXXX/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/XXXXXX/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /XXXXXX/node_modules/electron-rebuild/lib/src/cli.js:146:9
```

**Comment by malept** [comment]
That looks like a compile error, not a error with electron-rebuild itself. It's possible that `better-sqlite3` does not compile with whatever version of Electron you're using or whatever C++ compiler/stdlib you're using.

**Comment by malept** [comment]
Yep, this is an upstream problem: https://github.com/JoshuaWise/better-sqlite3/issues/494
