### ISSUE TITLE
MSBuild unexpected CL task error

### ISSUE THREAD

**Issue by MattiooFR** [electron/electron-rebuild#58]
Hi, 
I have no idea what's is going on, but it seems I can't rebuild electron package anymore ..
Everytime I try this command 

./node_modules/.bin/electron-rebuild.cmd

I get this error : 

> bluetooth-serial-port@1.2.6 install C:\PROJET\lhc-electron\node_modules\lhc-se
rvice\node_modules\webblue\node_modules\bluetooth-serial-port
> node-gyp configure build

> C:\PROJET\lhc-electron\node_modules\lhc-service\node_modules\webblue\node_module
> s\bluetooth-serial-port>if not defined npm_config_node_gyp (node "C:\PROJET\lhc-
> electron\node_modules\electron-rebuild\node_modules\npm\bin\node-gyp-bin\\..\..\
> node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configur
> e build )
> G?n?ration des projets individuellement dans cette solution. Pour activer la g?n
> ?ration en parall?le, ajoutez le commutateur "/m".
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018: ?chec inattendu de la t?che "CL". [C:\PROJET\lhc-elect
> ron\node_modules\lhc-service\node_modules\webblue\node_modules\bluetooth-serial-
> port\build\BluetoothSerialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018: System.TypeInitializationException: Une exception a ?t
> ? lev?e par l'initialiseur de type pour 'Microsoft.Build.Utilities.FileTracker'.
>  ---> System.IO.FileNotFoundException: Le fichier sp?cifi? est introuvable. (Exc
> eption de HRESULT : 0x80070002) [C:\PROJET\lhc-electron\node_modules\lhc-service
> \node_modules\webblue\node_modules\bluetooth-serial-port\build\BluetoothSerialPo
> rt.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? System.Runtime.InteropServices.Marshal.ThrowExcep
> tionForHRInternal(Int32 errorCode, IntPtr errorInfo) [C:\PROJET\lhc-electron\nod
> e_modules\lhc-service\node_modules\webblue\node_modules\bluetooth-serial-port\bu
> ild\BluetoothSerialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? Microsoft.Build.Shared.NativeMethodsShared.ThrowE
> xceptionForErrorCode(Int32 errorCode) [C:\PROJET\lhc-electron\node_modules\lhc-s
> ervice\node_modules\webblue\node_modules\bluetooth-serial-port\build\BluetoothSe
> rialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? Microsoft.Build.Shared.NativeMethodsShared.GetSho
> rtFilePath(String path) [C:\PROJET\lhc-electron\node_modules\lhc-service\node_mo
> dules\webblue\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxpr
> oj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? Microsoft.Build.Utilities.FileTracker..cctor() [C
> :\PROJET\lhc-electron\node_modules\lhc-service\node_modules\webblue\node_modules
> \bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    --- Fin de la trace de la pile d'exception interne
> --- [C:\PROJET\lhc-electron\node_modules\lhc-service\node_modules\webblue\node_m
> odules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? Microsoft.Build.CPPTasks.CL.ComputeOutOfDateSourc
> es() [C:\PROJET\lhc-electron\node_modules\lhc-service\node_modules\webblue\node_
> modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? Microsoft.Build.CPPTasks.TrackedVCToolTask.SkipTa
> skExecution() [C:\PROJET\lhc-electron\node_modules\lhc-service\node_modules\webb
> lue\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? Microsoft.Build.Utilities.ToolTask.Execute() [C:\
> PROJET\lhc-electron\node_modules\lhc-service\node_modules\webblue\node_modules\b
> luetooth-serial-port\build\BluetoothSerialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? Microsoft.Build.CPPTasks.TrackedVCToolTask.Execut
> e() [C:\PROJET\lhc-electron\node_modules\lhc-service\node_modules\webblue\node_m
> odules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? Microsoft.Build.BackEnd.TaskExecutionHost.Microso
> ft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\PROJET\lhc-electron\node_modul
> es\lhc-service\node_modules\webblue\node_modules\bluetooth-serial-port\build\Blu
> etoothSerialPort.vcxproj]
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targe
> ts(341,5): error MSB4018:    ? Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInsta
> ntiatedTask>d__20.MoveNext() [C:\PROJET\lhc-electron\node_modules\lhc-service\no
> de_modules\webblue\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.
> vcxproj]
> 
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
> ed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\PROJET\lhc-electron\node_modules\e
> lectron-rebuild\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
> s.js:200:12)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\PROJET\\lhc-electron
> \\node_modules\\electron-rebuild\\node_modules\\npm\\node_modules\\node-gyp\\bin
> \\node-gyp.js" "configure" "build"
> gyp ERR! cwd C:\PROJET\lhc-electron\node_modules\lhc-service\node_modules\webblu
> e\node_modules\bluetooth-serial-port
> gyp ERR! node -v v4.4.2
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> 
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\PROJET\\lhc-electron\\n
> ode_modules\\electron-rebuild\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--
> runtime=electron" "--target=0.36.12" "--arch=x64"
> npm ERR! node v4.4.2
> npm ERR! npm  v3.8.5
> npm ERR! code ELIFECYCLE
> npm ERR! bluetooth-serial-port@1.2.6 install: `node-gyp configure build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bluetooth-serial-port@1.2.6 install script 'node-gyp conf
> igure build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the bluetooth-serial-port
>  package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp configure build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs bluetooth-serial-port
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls bluetooth-serial-port
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\PROJET\lhc-electron\node_modules\npm-debug.log
> 
> Process exited with code: 1
> Error: Process exited with code: 1
>     at ChildProcess.<anonymous> (C:\PROJET\lhc-electron\node_modules\electron-re
> build\lib\spawn.js:55:26)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

It seems that it's a MSBuild error, I tryed to reinstall Visual Express 2013, node 4.4.2, python 2.7.11, electron etc,still the same issue stucked in ....

If you have any idea that would be great, thanks !

**Comment by MattiooFR** [comment]
Ok I think it was conflict into my computer because of multiple install and uninstall, after a full reset everything work properly, Closed !
