### ISSUE TITLE
503 stack Error on Windows

### ISSUE THREAD

**Issue by bredele** [electron/electron-rebuild#580]
Hi,

I am running an Electron project with a dependency using serialport. I need to compile it for windows but I keep getting the following issue:

Electron: 7.3.3
Elecyton-rebuild: 21.2.0

```sh
An unhandled error occurred inside electron-rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 503 response downloading https://www.electronjs.org/headers/v7.3.3/node-v7.3.3-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (C:\Users\olivi\Documents\GitHub\MYPRIVATEREPO\node_modules\node-gyp\lib\install.js:188:14)
gyp ERR! stack     at Request.emit (events.js:327:22)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\olivi\Documents\GitHubMYPRIVATEREPO\node_modules\request\request.js:1059:10)
gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:509:22)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at addChunk (internal/streams/readable.js:309:12)
gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:284:9)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "C:\\Users\\olivi\\Documents\\GitHub\\MYPRIVATEREPO\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=7.3.3" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\olivi\Documents\GitHubMYPRIVATEREPO\node_modules\@bredele\MYOTHERPRIVATEREPO\node_modules\@serialport\bindings
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 503 response downloading https://www.electronjs.org/headers/v7.3.3/node-v7.3.3-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (C:\Users\olivi\Documents\GitHub\MYPRIVATEREPO\node_modules\node-gyp\lib\install.js:188:14)

```
I am a bit stuck. Do I need to run electron-rebuild in the dependency or my electron project? Is it possible to rebuild on Mac and create a Windows distrib?

**Comment by malept** [comment]
This was a temporary issue with the `electronjs.org` website, it should be operational again.
