### ISSUE TITLE
Not working on Electron 1.0.1

### ISSUE THREAD

**Issue by parro-it** [electron/electron-rebuild#66]
After upgrading to `Electron` 1.0.1, I receive these errors:

```bash
ENOENT: no such file or directory, stat '/home/parroit/Desktop/repos/tunnels/node_modules/electron-rebuild/lib/headers/.node-gyp/1.0.1/common.gypi'
Error: ENOENT: no such file or directory, stat '/home/parroit/Desktop/repos/tunnels/node_modules/electron-rebuild/lib/headers/.node-gyp/1.0.1/common.gypi'
    at Error (native)
```

Looking at `/home/parroit/Desktop/repos/tunnels/node_modules/electron-rebuild/lib/headers/.node-gyp`, it only contains an `iojs-1.0.1` folder.

I'm not sure if you yet have to publish a version that support the new `Electron` release, or if there is some confusion between versions...

**Comment by jostrander** [comment]
So I've done some research on this, and I think the dist-url https://atom.io/download/atom-shell is accidentally resolving 1.0.1 to iojs-1.0.1 instead of electron v1.0.1. I think @zcbenz maintains that portion by the way it redirects to a bucket with his username. Maybe he can take a peek at this and fix this server side. 

Normally node-gyp would actually download node headers, but in the case of electron, node gyp needs to download the node headers that electron is using so that's where the custom dist-url comes in:

For reference:

With dist-url set to atom.io and node version set to 1.0.1:
```
~/test-electron-rebuild/electron-rebuild(master ✗) /home/jesse/test-electron-rebuild/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js install --target=1.0.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.10.0 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v1.0.1/iojs-v1.0.1.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v1.0.1/iojs-v1.0.1.tar.gz
gyp http GET https://atom.io/download/atom-shell/v1.0.1/SHASUMS256.txt
gyp http 200 https://atom.io/download/atom-shell/v1.0.1/SHASUMS256.txt
1.0.1
gyp info ok 
```
With dist-url not set and node version set to 1.0.1
```
~/test-electron-rebuild/electron-rebuild(master ✗) /home/jesse/test-electron-rebuild/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js install --target=1.0.1 --arch=x64 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.10.0 | linux | x64
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
gyp http GET https://iojs.org/dist/v1.0.1/iojs-v1.0.1.tar.gz
gyp http 200 https://iojs.org/dist/v1.0.1/iojs-v1.0.1.tar.gz
gyp http GET https://iojs.org/dist/v1.0.1/SHASUMS256.txt
gyp http 200 https://iojs.org/dist/v1.0.1/SHASUMS256.txt
1.0.1
gyp info ok 
```
With node version set to 5.10.0 and dist not set:
```
~/test-electron-rebuild/electron-rebuild(master ✗) /home/jesse/test-electron-rebuild/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js install --target=1.0.1 --arch=x64 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.10.0 | linux | x64
gyp WARN download NVM_IOJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use IOJS_ORG_MIRROR
gyp http GET https://iojs.org/dist/v1.0.1/iojs-v1.0.1.tar.gz
gyp http 200 https://iojs.org/dist/v1.0.1/iojs-v1.0.1.tar.gz
gyp http GET https://iojs.org/dist/v1.0.1/SHASUMS256.txt
gyp http 200 https://iojs.org/dist/v1.0.1/SHASUMS256.txt
1.0.1
gyp info ok 
```

And finally with node version set to 5.10.0 and dist set:
```
~/test-electron-rebuild/electron-rebuild(master ✗) /home/jesse/test-electron-rebuild/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js install --target=5.10.0 --arch=x64 --dist-url=https://atom.io/download/atom-shell
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.10.0 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v5.10.0/node-v5.10.0-headers.tar.gz
gyp http 403 https://atom.io/download/atom-shell/v5.10.0/node-v5.10.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v5.10.0/node-v5.10.0-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/jesse/test-electron-rebuild/electron-rebuild/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:95:20)
gyp ERR! stack     at Request.emit (events.js:182:7)
gyp ERR! stack     at Request.onRequestResponse (/home/jesse/test-electron-rebuild/electron-rebuild/node_modules/npm/node_modules/request/request.js:977:10)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at ClientRequest.emit (events.js:182:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:458:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:348:20)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! System Linux 3.13.0-52-generic
gyp ERR! command "/home/jesse/.nvm/versions/node/v5.10.0/bin/node" "/home/jesse/test-electron-rebuild/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=5.10.0" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /home/jesse/test-electron-rebuild/electron-rebuild
gyp ERR! node -v v5.10.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

**Comment by MarshallOfSound** [comment]
@jostrander Just woke up and saw all the builds were failing :cry: 

This is why :laughing: 

It looks to just be a dodgily configured redirect that was setup to expect electron version to be `0.X.Y` but wasn't ready to handle `1.X.Y`

/cc @zcbenz

**Comment by jostrander** [comment]
Looks like this  might be a client side issue that wasn't though of before upgrading to `^1.0.0` semver. Here is the file in question with the lines that could be causing the issue:

https://github.com/nodejs/node-gyp/blob/master/lib/process-release.js#L50
https://github.com/nodejs/node-gyp/blob/master/lib/process-release.js#L105-L116

**Comment by MarshallOfSound** [comment]
@jostrander I have made an upstream PR to node-gyp to implement a feature that will get this fixed in this repo.

See https://github.com/nodejs/node-gyp/pull/927

**Comment by parro-it** [comment]
@MarshallOfSound I saw you closed your PR because issue has been fixed server side... I tried but still getting `iojs-1.0.1` file. 

Also tried to manually rename it to expected `1.0.1` (because I thought they could be Electron correct headers with just wrong filename), but no luck...

Did you manage to do a succesfull recompilation?

**Comment by MarshallOfSound** [comment]
@parro-it I'm about to submit a PR to this repo to fix it.  Just testing now, give me a few minutes :+1:

**Comment by parro-it** [comment]
No worries @MarshallOfSound, I'm just investigating if I'm doing something wrong, 
thank you!

**Comment by micheletedeschi** [comment]
I've renamed iojs-1.0.2 in 1.0.2 and the execute eletron-rebuild and work for me

```
mv ./node_modules/electron-rebuild/lib/headers/.node-gyp/iojs-1.0.2 ./node_modules/electron-rebuild/lib/headers/.node-gyp/1.0.2

./node_modules/.bin/electron-rebuild -f sqlite3
```

**Comment by MarshallOfSound** [comment]
@micheletedeschi That is what the PR #67 handles

**Comment by angelxmoreno** [comment]
lets get this PR merged
