### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by atdrago** [electron/electron-rebuild#70]
I've been getting this strange error referencing `console.log(process.versions.modules)` the past few days in my Travis builds. Just noticed it this morning locally. It happens after I run `./node_modules/.bin/electron-rebuild`

I'm running Node v6.1.0, electron-prebuilt v1.2.0, and electron-rebuild v1.1.4 (though it seems to be happening with all electron-rebuild v1.1.x).

![screen shot 2016-05-27 at 10 23 43 am](https://cloud.githubusercontent.com/assets/144225/15615858/73629390-23f5-11e6-8c39-a8e4a66532fc.png)

I don't believe I changed anything for this to happen, besides doing an `npm install` this morning. Any ideas what's going on here?

**Comment by lselden** [comment]
I just experienced the same problem when running my electron app (not when running electron-rebuild itself). It was because of electron using `const { app } = require('electron')` instead of `const app = require('app')`. Maybe this applies to your error?

**Comment by atdrago** [comment]
I *am* doing that in my app, but I don't see how it could be related. My app isn't running, this is just happening in my `postinstall`.

**Comment by atdrago** [comment]
So this seems to only be happening with electron-prebuilt 1.2.0. I'll go ahead and close this, and move to electron-prebuilt's Issues section.

**Comment by kevinsawicki** [comment]
@atdrago can you try upgrading to `electron-rebuild@1.1.5`?

**Comment by atdrago** [comment]
@kevinsawicki `electron-rebuild@1.1.5` runs now without error, though it doesn't seem to be working, as now I'm getting an error with `nodobjc` on app launch.

Correct me if I'm wrong, but this is the type of error I'd see if I hadn't run `electron-rebuild` post install, right?

```
Uncaught Exception:
TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument
    at TypeError (native)
    at Object.writePointer (/Users/adamdrago/Documents/git/negative/node_modules/ref/lib/ref.js:742:11)
    at Object.set (/Users/adamdrago/Documents/git/negative/node_modules/ref/lib/ref.js:484:13)
    at Object.alloc (/Users/adamdrago/Documents/git/negative/node_modules/ref/lib/ref.js:516:13)
    at Object.proxy [as objc_getClassList] (/Users/adamdrago/Documents/git/negative/node_modules/ffi/lib/_foreign_function.js:50:22)
    at Object.getClassList (/Users/adamdrago/Documents/git/negative/node_modules/nodobjc/lib/core.js:111:20)
    at Object.importFramework (/Users/adamdrago/Documents/git/negative/node_modules/nodobjc/lib/import.js:321:26)
    at Function.framework (/Users/adamdrago/Documents/git/negative/node_modules/nodobjc/lib/index.js:225:18)
    at Object.<anonymous> (/Users/adamdrago/Documents/git/negative/lib/negative.js:33:6)
    at Module._compile (module.js:541:32)
```

**Comment by kevinsawicki** [comment]
> TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument

Hmm, not sure, this isn't an error I've seen with modules being incompatible in the past, usually it is something like `Module did not self-register` or `Module version mismatch. Expected X, got Y`

**Comment by atdrago** [comment]
Ah, right. And it looks like this error already has an (old) issue over at NodObjC https://github.com/TooTallNate/NodObjC/issues/48

I'll follow up there. Thanks again!

**Comment by imlliu2005** [comment]
@atdrago Hi atdrago I have a problem when my electron from 1.1.1 update to 1.2.1 when it use nodobjc call objective-c framework like this: 
 app threw an error during load
TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument
    at TypeError (native)
    at Object.writePointer (/Users/apple/talk/electron-quick-start-master/node_modules/ref/lib/ref.js:742:11)
    at Object.set (/Users/apple/talk/electron-quick-start-master/node_modules/ref/lib/ref.js:484:13)
    at Object.alloc (/Users/apple/talk/electron-quick-start-master/node_modules/ref/lib/ref.js:516:13)
    at Object.proxy [as objc_getClassList] (/Users/apple/talk/electron-quick-start-master/node_modules/ffi/lib/_foreign_function.js:50:22)
    at Object.getClassList (/Users/apple/talk/electron-quick-start-master/node_modules/nodobjc/lib/core.js:111:20)
    at Object.importFramework (/Users/apple/talk/electron-quick-start-master/node_modules/nodobjc/lib/import.js:321:26)
    at Function.framework (/Users/apple/talk/electron-quick-start-master/node_modules/nodobjc/lib/index.js:225:18)
    at Object.<anonymous> (/Users/apple/talk/electron-quick-start-master/main.js:14:9)
   ^C

**Comment by imlliu2005** [comment]
@atdrago I see you also have this problem，and you resolve it.
How to deal with it. thanks.

**Comment by atdrago** [comment]
@imlliu2005 Honestly, I've sort of been waiting to see if other people have the issue before I move forward seeking the solution. I didn't want to cause a stir if it's just an issue in my code.

I've stayed on 1.1.3 until I have time to figure out where to put this. This seems to be a common issue with NodObjC as there are [several open issues](https://github.com/TooTallNate/NodObjC/issues?utf8=✓&q=is%3Aissue+is%3Aopen+writepointer) that have something to do with `writePointer`. [You can look here](https://github.com/TooTallNate/NodObjC/issues/50) for a common fix, but I'm guessing that won't help either. This situation feels different, because this error gets thrown for me when I do:
```js
const $ = require('nodobjc');
$.framework('Cocoa');
```

Nothing too advanced. And it only happens on versions of Electron >= 1.2.0. 

It's a NodObjC issue caused by an update to Electron. So I have no idea where to put the "blame." Maybe @TooTallNate can comment.

I'll update this thread if I find a fix. Sorry I'm not more help.

**Comment by imlliu2005** [comment]
@atdrago  Thank you all the same,I will ask TooTallNate for help,if I resolve this I will tell you
