### ISSUE TITLE
 warning C4005: 'NAPI_VERSION': macro redefinition and  warning C4005: 'NAPI_VERSION': macro redefinition

### ISSUE THREAD

**Issue by zhex900** [electron/electron-rebuild#716]
Hi,

I am trying to rebuild `aws-crt` for electron on windows. 

The forked repo is here https://github.com/zhex900/aws-crt-nodejs.

I have created `binding.gyp`. `node-gyp build` works fine. No errors. 

But when I run `.\node_modules\.bin\electron-rebuild.cmd`

I get the following errors. Can you help me to build it?

````
PS C:\Code\aws-crt-nodejs> .\node_modules\.bin\electron-rebuild.cmd
/ Building module: aws-crt-nodejs, Completed: 0gyp info find Python using Python version 3.7.9 found at "C:\Users\jake\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe"
- Building module: aws-crt-nodejs, Completed: 0gyp http GET https://www.electronjs.org/headers/v13.1.2/node-v13.1.2-headers.tar.gz
/ Building module: aws-crt-nodejs, Completed: 0gyp http 200 https://www.electronjs.org/headers/v13.1.2/node-v13.1.2-headers.tar.gz
| Building module: aws-crt-nodejs, Completed: 0gyp http GET https://www.electronjs.org/headers/v13.1.2/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v13.1.2/win-x86/node.lib
gyp http GET https://www.electronjs.org/headers/v13.1.2/win-x64/node.lib
gyp http GET https://www.electronjs.org/headers/v13.1.2/win-arm64/node.lib
\ Building module: aws-crt-nodejs, Completed: 0gyp http 200 https://www.electronjs.org/headers/v13.1.2/SHASUMS256.txt
gyp http 200 https://www.electronjs.org/headers/v13.1.2/win-x64/node.lib
gyp http 200 https://www.electronjs.org/headers/v13.1.2/win-x86/node.lib
gyp http 200 https://www.electronjs.org/headers/v13.1.2/win-arm64/node.lib
- Building module: aws-crt-nodejs, Completed: 0gyp info find VS using VS2019 (16.10.31402.337) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\jake\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Code\\aws-crt-nodejs\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Code\\aws-crt-nodejs\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Code\\aws-crt-nodejs\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jake\\.electron-gyp\\13.1.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jake\\.electron-gyp\\13.1.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Code\\aws-crt-nodejs\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\jake\\\\.electron-gyp\\\\13.1.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Code\\aws-crt-nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Code\\aws-crt-nodejs\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
| Building module: aws-crt-nodejs, Completed: 0gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64',
gyp info spawn args   map: [Function (anonymous)]
gyp info spawn args ]
/ Building module: aws-crt-nodejs, Completed: 0Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
| Building module: aws-crt-nodejs, Completed: 0  auth.c
/ Building module: aws-crt-nodejs, Completed: 0C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\auth.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-nodejs\buil
d\aws-crt.vcxproj]
\ Building module: aws-crt-nodejs, Completed: 0  class_binder.c
| Building module: aws-crt-nodejs, Completed: 0C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\class_binder.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-nod
ejs\build\aws-crt.vcxproj]
/ Building module: aws-crt-nodejs, Completed: 0  crypto.c
C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\crypto.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-nodejs\bu
ild\aws-crt.vcxproj]
- Building module: aws-crt-nodejs, Completed: 0  http_connection.c
C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
\ Building module: aws-crt-nodejs, Completed: 0C:\Code\aws-crt-nodejs\source\http_connection.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-
nodejs\build\aws-crt.vcxproj]
  http_connection_manager.c
| Building module: aws-crt-nodejs, Completed: 0C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\http_connection_manager.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\
aws-crt-nodejs\build\aws-crt.vcxproj]
/ Building module: aws-crt-nodejs, Completed: 0  http_headers.c
C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\http_headers.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-nod
ejs\build\aws-crt.vcxproj]
- Building module: aws-crt-nodejs, Completed: 0  http_message.c
C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\http_message.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-nod
ejs\build\aws-crt.vcxproj]
\ Building module: aws-crt-nodejs, Completed: 0  http_stream.c
| Building module: aws-crt-nodejs, Completed: 0C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\http_stream.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-node
js\build\aws-crt.vcxproj]
  io.c
/ Building module: aws-crt-nodejs, Completed: 0C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\io.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-nodejs\build\
aws-crt.vcxproj]
- Building module: aws-crt-nodejs, Completed: 0  logger.c
C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\logger.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-nodejs\bu
ild\aws-crt.vcxproj]
\ Building module: aws-crt-nodejs, Completed: 0  module.c
C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-nodejs\bu
ild\aws-crt.vcxproj]
| Building module: aws-crt-nodejs, Completed: 0C:\Code\aws-crt-nodejs\source\module.c(543,18): warning C4229: anachronism used: modifiers on data are ignored [C:\Code
\aws-crt-nodejs\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2143: syntax error: missing '{' before '-' [C:\Code\aws-crt-node
js\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2059: syntax error: '-' [C:\Code\aws-crt-nodejs\build\aws-crt.vc
xproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2143: syntax error: missing ')' before '-' [C:\Code\aws-crt-node
js\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2165: 'left-side modifier': cannot modify pointers to data [C:\C
ode\aws-crt-nodejs\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2059: syntax error: ')' [C:\Code\aws-crt-nodejs\build\aws-crt.vc
xproj]
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Code\aws-crt-nodejs'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1



Error: node-gyp failed to rebuild 'C:\Code\aws-crt-nodejs'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1


    at ModuleRebuilder.rebuildNodeGypModule (C:\Code\aws-crt-nodejs\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Rebuilder.rebuildModuleAt (C:\Code\aws-crt-nodejs\node_modules\electron-rebuild\lib\src\rebuild.js:190:9)
    at async Rebuilder.rebuild (C:\Code\aws-crt-nodejs\node_modules\electron-rebuild\lib\src\rebuild.js:152:17)
    at async C:\Code\aws-crt-nodejs\node_modules\electron-rebuild\lib\src\cli.js:146:9
`````

Now if run ` node-gyp build` I will see the same errors as before. I am guessing it is something to do with the configuration or environmental variables. 

````
PS C:\Code\aws-crt-nodejs> node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@8.1.0
gyp info using node@14.17.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  module.c
C:\Code\aws-crt-nodejs\source\module.h(13,1): warning C4005: 'NAPI_VERSION': macro redefinition [C:\Code\aws-crt-nodejs
\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c : message : see previous definition of 'NAPI_VERSION' [C:\Code\aws-crt-nodejs\bu
ild\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): warning C4229: anachronism used: modifiers on data are ignored [C:\Code
\aws-crt-nodejs\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2143: syntax error: missing '{' before '-' [C:\Code\aws-crt-node
js\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2059: syntax error: '-' [C:\Code\aws-crt-nodejs\build\aws-crt.vc
xproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2143: syntax error: missing ')' before '-' [C:\Code\aws-crt-node
js\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2165: 'left-side modifier': cannot modify pointers to data [C:\C
ode\aws-crt-nodejs\build\aws-crt.vcxproj]
C:\Code\aws-crt-nodejs\source\module.c(543,18): error C2059: syntax error: ')' [C:\Code\aws-crt-nodejs\build\aws-crt.vc
xproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jake\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jake\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Code\aws-crt-nodejs
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v8.1.0
gyp ERR! not ok
````

**Comment by zhex900** [comment]
I will try to use `cmake.js`
