### ISSUE TITLE
problem when rebuilding gdal

### ISSUE THREAD

**Issue by hail-kang** [electron/electron-rebuild#734]
# Version
* node = 14.16.1
* npm = 6.14.12
* windows-build-tools = 5.2.2 (I installed it with the command "npm install --vs2015 --global windows-build-tools")
* electron = 13.1.4
* electron-rebuild = 2.3.5
* gdal = 0.10.1

# Issue
it's part of my electron project's package.json
```json
"devDependencies": {
    "electron": "^13.1.4",
    "electron-rebuild": "^2.3.5"
  },
  "dependencies": {
    "gdal": "^0.10.1"
  }
```

I referenced the link below. 
https://www.electronjs.org/docs/tutorial/using-native-node-modules

* npm config set msvs_version=2015
* set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140
* fixed to 'win_delay_load_hook': 'true'  in binding.gyp of gdal

However, when the following command was executed, an error occurred while compiling. 
".\node_modules\.bin\electron-rebuild.cmd"

# Error
c:\users\pc\.electron-gyp\13.1.4\include\node\v8.h(1652): error C2059: syntax error: '' [C:\Users\pc\Desktop\electron_gdal\nod
e_modules\gdal\build\gdal.vcxproj]
c:\users\pc\.electron-gyp\13.1.4\include\node\v8.h(1654): error C2238: ';' Unexpected token in front. [C:\Users\pc\Desktop\ele
ctron_gdal\node_modules\gdal\build\gdal.vcxproj]
c:\users\pc\.electron-gyp\13.1.4\include\node\v8.h(1670): error C2061: syntax error: identifier 'ResolveCallback' [C:\Users\pc\Deskto
p\electron_gdal\node_modules\gdal\build\gdal.vcxproj]
c:\users\pc\.electron-gyp\13.1.4\include\node\v8.h(7292): error C2059: syntax error: '' [C:\Users\pc\Desktop\electron_gdal\nod
e_modules\gdal\build\gdal.vcxproj]
c:\users\pc\.electron-gyp\13.1.4\include\node\v8.h(8652): error C2061: syntax error: identifier 'HostImportModuleDynamicallyCallback'
 [C:\Users\pc\Desktop\electron_gdal\node_modules\gdal\build\gdal.vcxproj]

...

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Users\pc\Desktop\electron_gdal\node_modules\gdal'.
Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1

Error: node-gyp failed to rebuild 'C:\Users\pc\Desktop\electron_gdal\node_modules\gdal'.
Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1

    at ModuleRebuilder.rebuildNodeGypModule (C:\Users\pc\Desktop\electron_gdal\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (C:\Users\pc\Desktop\electron_gdal\node_modules\electron-rebuild\lib\src\rebuild.js:190:9)
    at async Rebuilder.rebuild (C:\Users\pc\Desktop\electron_gdal\node_modules\electron-rebuild\lib\src\rebuild.js:152:17)
    at async C:\Users\pc\Desktop\electron_gdal\node_modules\electron-rebuild\lib\src\cli.js:146:9

**Comment by sanperrier** [comment]
Has the same with `diskusage`

**Comment by mithusingh32** [comment]
Sounds like it's just not those. 
Having similar issue w/ `pouchdb` and `sql3lite` on Linux.

**Comment by VadimCiv** [comment]
I have same issue. On windows can't compile gdal
But on my MacBook M1 it's works perfect.
