### ISSUE TITLE
Support latest Visual Studio Update 3 (npm 3.10)

### ISSUE THREAD

**Issue by dbellavista** [electron/electron-rebuild#82]
Hi!

Due to a breaking upgrade of VS 2015, node-gyp stopped working and need to be updated to 3.4.10

In order to support that, NPM should be updated to `3.10.3`

**Comment by aelana** [comment]
Is this why even after clearing out node_modules, updating npm and updating the global node-gyp to latest as well as npm's node-gyp I still get the following when installing electron-rebuild?  If so is there a workaround as this has cause a rather big problem for me.

```
$ npm install electron-rebuild

> nslog@3.0.0 install G:\windows-worker-1\launcher-build-windows\build\Launcher\node_modules\nslog
> node-gyp rebuild


G:\windows-worker-1\launcher-build-windows\build\Launcher\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Users\buildbot\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
  win_delay_load_hook.c
C:\Users\buildbot\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [G:\windows-worker-1\launcher-build-windows\build\Launcher\node_modules\nslog\build\nslog.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\buildbot\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\buildbot\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\windows-worker-1\launcher-build-windows\build\Launcher\node_modules\nslog
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\buildbot\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-rebuild"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\windows-worker-1\launcher-build-windows\build\Launcher\npm-debug.log
```

**Comment by dbellavista** [comment]
That's the error :) you have to use the newest nodegyp shipped with npm
3.10 to support vs 2015 3

**Comment by aelana** [comment]
I thought I had been but it turns out there were old cached versions that kept overriding I cleared out all the various places windows hides node modules (%USERDATA%, program files, local directory, etc...) and I think I am past the problem.

**Comment by daguej** [comment]
Also seeing this.  Emptying node_modules did not help.

node v6.3.1
npm v3.10.3
node-gyp v3.4.0
msbuild 14.0.25420.1

**Comment by CoDanny** [comment]
I'm seeing this too :( @aelana could you let us know exactly which directories you needed to clear out?

**Comment by sweetim** [comment]
i am experiencing the same problem, it fails to rebuild after i update VS update 3, can you detail your steps how you manage to solve it?

**Comment by aelana** [comment]
In the end I think I was able to get it to work via setting the environment variable `npm_config_node_gyp` to point to the node-gyp.js I wanted it to use.

**Comment by MarshallOfSound** [comment]
Considering I (and many others) are on VS2015 Update 3 with no issues at the moment I can assume that the dependency chain resolves to a working set of modules now 👍
