### ISSUE TITLE
Canary file 'common.gypi' doesn't exist

### ISSUE THREAD

**Issue by natevw** [electron/electron-rebuild#9]
Getting this error trying to rebuild my dependencies (`npm install && electron-rebuild` with "./node_modules/.bin" in path):

```
Error: Canary file 'common.gypi' doesn't exist
    at checkForInstalledHeaders$ (/Users/natevw/…/my-app/node_modules/electron-rebuild/lib/main.js:58:15)
    at tryCatch (/Users/natevw/Desktop/…/my-app/node_modules/electron-rebuild/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/natevw/…/my-app/node_modules/electron-rebuild/node_modules/babel-core/node_modules/regenerator/runtime.js:305:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/natevw/…/my-app/node_modules/electron-rebuild/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
    at invoke (/Users/natevw/…/my-app/node_modules/node_modules/electron-rebuild/node_modules/babel-core/node_modules/regenerator/runtime.js:132:37)
    at /Users/natevw/…/my-app/node_modules/node_modules/electron-rebuild/node_modules/babel-core/node_modules/regenerator/runtime.js:166:18
    at run (/Users/natevw/…/my-app/node_modules/node_modules/electron-rebuild/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /Users/natevw/…/my-app/node_modules/node_modules/electron-rebuild/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at process._tickCallback (node.js:355:11)
```

My package.json is:

```
{
  "name": "some-app",
  "private": true,
  "version": "0.0.0",
  "description": "Some App",
  "repository": {
    "type": "git",
    "url": "…"
  },
  "main": "backend.js",
  "dependencies": {
    "d3": "^3.4.11",
    "fermata": "git://github.com/natevw/fermata.git#upcoming",
    "keytar": "^2.0.3",
    "node-hid": "https://github.com/natevw/node-hid/releases/download/test-node-12/node-hid-0.3.2.tgz"
  },
  "devDependencies": {
    "electron-prebuilt": "^0.26.0",
    "electron-rebuild": "^0.1.4"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "while :; do ~/Downloads/atom-shell-v0.17.2-darwin-x64/Atom.app/Contents/MacOS/Atom .; done"
  },
  "author": "Nathan Vander Wilt"
}
```

**Comment by natevw** [comment]
Still getting this after updating to node-hid@0.4.0. Is this likely a problem with a dependency, or something with electron itself? (node v0.12.2, btw)

**Comment by paulcbetts** [comment]
Give this a try on v0.2.3

**Comment by paulcbetts** [comment]
Reopen if it's still a bug!

**Comment by ahallicks** [comment]
I am now having this issue on anything after 1.1.0.

**Comment by paulcbetts** [comment]
@ahallicks Are you running the latest version of electron-rebuild?

**Comment by ahallicks** [comment]
I am indeed. Currently on 1.1.5.

**Comment by ahallicks** [comment]
For reference here's the full output of the error I get:

```
Canary file 'common.gypi' doesn't exist
Error: Canary file 'common.gypi' doesn't exist
    at checkForInstalledHeaders$ (C:\Development\TimeTracker\node_modules\electron-rebuild\lib\main.js:62:15)
    at tryCatch (C:\Development\TimeTracker\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Development\TimeTracker\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Development\TimeTracker\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at tryCatch (C:\Development\TimeTracker\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at invoke (C:\Development\TimeTracker\node_modules\babel-runtime\regenerator\runtime.js:146:20)
    at C:\Development\TimeTracker\node_modules\babel-runtime\regenerator\runtime.js:191:11
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (C:\Development\TimeTracker\node_modules\core-js\library\modules\$.export.js:30:36)
    at callInvokeWithMethodAndArg (C:\Development\TimeTracker\node_modules\babel-runtime\regenerator\runtime.js:190:16)
    at AsyncIterator.enqueue (C:\Development\TimeTracker\node_modules\babel-runtime\regenerator\runtime.js:211:37)
```

**Comment by ahallicks** [comment]
Okay, I think I've figured out why I get the issue now. I had a postinstall script that ran:

```
"postinstall": ".\\node_modules\\.bin\\electron-rebuild.cmd"
```

so that it automatically did the rebuilt on install. This seems to be where things went wrong as, when I manually run `.\node_modules\.bin\.electron-rebuild.cmd` after `npm install` everything works just fine.

**Comment by IsaiahJTurner** [comment]
Any fix?

**Comment by davydany** [comment]
Experiencing this bug too..

```
Windows 10; Version 1511, Build 10586.713
Node 4.1.1
Electron 1.4.12

# not sure if this is needed, but I noticed it another bug related to this that was closed, so i'm posting it here
Python 2.7.12 
```

**Comment by harshjv** [comment]
On macOS, I faced the same problem, but after installing full Xcode and reinstalling dependencies fixed this issue.

**Comment by MarshallOfSound** [comment]
This issue should no longer exist in the new `electron-rebuild`.  (The relevant code is no longer present)
