### ISSUE TITLE
node-abi missing from electron 17.X

### ISSUE THREAD

**Issue by hgouveia** [electron/electron-rebuild#994]
electron-rebuild: 3.2.7
Electron-Builder Version: 22.14.13
Node Version: v14.18.1
Electron Version: 17.1.0
Electron Type (current, beta, nightly): current
Target: windows

```
 • executing electron-rebuild electron=17.1.0 platform=windows arch=x64 appDir=D:\app\dist
  ⨯ Could not detect abi for version 17.1.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron  failedTask=build stackTrace=Error: Could not detect abi for version 17.1.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (D:\app\node_modules\node-abi\index.js:39:9)
    at Rebuilder.get ABI [as ABI] (D:\app\node_modules\electron-rebuild\src\rebuild.ts:124:33)
    at PrebuildInstall.prebuiltModuleExists (D:\app\node_modules\electron-rebuild\src\module-type\prebuild-install.ts:65:149)
    at ModuleRebuilder.prebuildInstallNativeModuleExists (D:\app\node_modules\electron-rebuild\src\module-rebuilder.ts:56:33)
    at Rebuilder.rebuildModuleAt (D:\app\node_modules\electron-rebuild\src\rebuild.ts:179:31)
    at Rebuilder.rebuild (D:\app\node_modules\electron-rebuild\src\rebuild.ts:158:9)
    at exports.default (D:\app\resources\beforeBuildHook.js:11:5)
    at Packager.installAppDependencies (D:\app\node_modules\app-builder-lib\src\packager.ts:499:51)
    at WinPackager.doPack (D:\app\node_modules\app-builder-lib\src\platformPackager.ts:216:5)
    at WinPackager.pack (D:\app\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (D:\app\node_modules\app-builder-lib\src\packager.ts:441:9)
    at Object.executeFinally (D:\app\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (D:\app\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (D:\app\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (D:\app\node_modules\builder-util\src\promise.ts:12:14)
  ```

**Comment by viaSeunghyun** [comment]
Same Issue.
I was install node-abi 3.5.0 but electron-rebuild could not detect.
